import { StyleSheet } from "react-native";
import { colors, radius, spacing } from "../../../theme";

export const cashStyles = StyleSheet.create({
  cashPanel: { flex: 1, minHeight: 0 },
  cashContent: { flex: 1, gap: spacing.sm },
  openingSection: {
    gap: spacing.xs,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  openingHeading: { alignItems: "center", justifyContent: "space-between" },
  openingEntry: { alignItems: "center", gap: spacing.sm },
  openingInput: { flex: 1, minWidth: 0, minHeight: 44 },
  openingInputLocked: { backgroundColor: colors.surfaceContainerLow },
  moneyInputText: { color: colors.success, fontSize: 19, fontWeight: "900" },
  moneyPrefix: { color: colors.success, fontSize: 15, fontWeight: "900" },
  openingSaveButton: {
    minWidth: 96,
    minHeight: 44,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  openingSaveText: { color: colors.white, fontSize: 12, fontWeight: "800" },
  tenderSection: { gap: spacing.sm },
  tenderHeading: { alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  quickGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  quickGridCompact: { flexWrap: "nowrap" },
  quickButton: {
    width: "30%",
    flexGrow: 1,
    minHeight: 42,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
  },
  quickButtonActive: { borderColor: colors.primary, backgroundColor: colors.surfaceTint },
  quickButtonText: { color: colors.ink, fontSize: 13, fontWeight: "800" },
  quickButtonTextTablet: { fontSize: 14 },
  quickButtonTextActive: { color: colors.primary },
  quickButtonCompact: { width: undefined, flexBasis: 0, minWidth: 0, paddingHorizontal: spacing.xs },
  tenderAmounts: { gap: spacing.sm, alignItems: "stretch" },
  amountBox: { flex: 1, minWidth: 0, gap: spacing.xs },
  tenderInput: { height: 48, minHeight: 48, borderColor: "#BFDBFE" },
  changeBox: {
    height: 48,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceContainerLow,
    justifyContent: "flex-end",
    alignItems: "center",
    gap: spacing.xs,
  },
  changeBoxReady: { backgroundColor: colors.successSoft },
  changeValue: { fontWeight: "700" },
  shortageValue: { color: colors.danger },
  displayLabel: {
    color: colors.inkSubtle,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  keypadGrid: { flex: 1, minHeight: 0, gap: spacing.sm },
  keypadGridMobile: { flex: 0, flexGrow: 0, flexShrink: 0 },
  keypadRow: {
    flex: 1,
    minHeight: 48,
    flexDirection: "row",
    alignItems: "stretch",
    position: "relative",
    marginHorizontal: -spacing.xs,
  },
  keypadRowMobile: { flex: 0, height: 44, minHeight: 44 },
  keypadCell: {
    flexGrow: 1,
    flexBasis: 0,
    minWidth: 0,
    paddingHorizontal: spacing.xs,
  },
  keypadButton: {
    flex: 1,
    minWidth: 0,
    minHeight: 48,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
  },
  keypadText: { color: colors.ink, fontSize: 19, fontWeight: "800" },
  keypadTextMobile: { fontSize: 17 },
  keypadClear: { borderColor: "#FECACA", backgroundColor: "#FFF7F7" },
  keypadClearText: { color: colors.danger },
  applyButton: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    right: spacing.xs,
    marginLeft: spacing.xs,
    minHeight: 48,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  applyButtonText: { color: colors.white, fontSize: 12, fontWeight: "900" },
  applyButtonTextTablet: { fontSize: 13 },
  disabledButton: { opacity: 0.5 },
  qrisPanel: { flex: 1, minHeight: 0 },
  verifyBox: {
    flex: 1,
    minHeight: 290,
    padding: 20,
    backgroundColor: "#FFFBEB",
    borderWidth: 1,
    borderColor: "#FDE68A",
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  verifyIcon: {
    width: 48,
    height: 48,
    borderRadius: 48,
    backgroundColor: "#FEF3C7",
    alignItems: "center",
    justifyContent: "center",
  },
  verifyTitle: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: "900",
    textAlign: "center",
  },
  verifyDescription: {
    color: "#475569",
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
    maxWidth: 420,
  },
  verifyAmount: { color: colors.success, fontWeight: "900" },
  verifyButton: {
    minHeight: 46,
    paddingHorizontal: 18,
    borderRadius: radius.pill,
    backgroundColor: "#FEF3C7",
    borderWidth: 1,
    borderColor: "#F59E0B",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 7,
  },
  verifyButtonDone: {
    backgroundColor: colors.successSoft,
    borderColor: "#86EFAC",
  },
  verifyButtonText: { color: "#B45309", fontSize: 12, fontWeight: "900" },
});
