import { StyleSheet } from "react-native";
import {
  colors,
  fieldHeight,
  radius,
  spacing,
  type,
  typography,
} from "../../../theme";

export const cashStyles = StyleSheet.create({
  cashPanel: { flex: 1, minHeight: 0 },
  cashPanelStacked: { flex: 0, minHeight: 0 },
  cashContent: { flex: 1, gap: spacing.sm },
  cashContentStacked: { flex: 0 },
  moneyInputText: { color: colors.ink, fontSize: type.amount, lineHeight: 25, fontWeight: "600" },
  moneyPrefix: { color: colors.ink, fontSize: type.bodySmall, lineHeight: 21, fontWeight: "600" },
  tenderSection: { gap: spacing.sm },
  tenderHeading: { alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  quickGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  quickGridCompact: { flexWrap: "nowrap" },
  quickButton: {
    width: "30%",
    flexGrow: 1,
    minHeight: 42,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
  },
  quickButtonActive: { borderColor: colors.primary, backgroundColor: colors.surfaceTint },
  quickButtonText: { color: colors.ink, ...typography.button },
  quickButtonTextTablet: { fontSize: type.button, lineHeight: 18 },
  quickButtonTextActive: { color: colors.primary },
  quickButtonCompact: { width: undefined, flexBasis: 0, minWidth: 0, paddingHorizontal: spacing.xs },
  tenderAmounts: { gap: spacing.sm, alignItems: "stretch" },
  tenderAmountsStacked: { flexDirection: "column" },
  amountBox: { flex: 1, minWidth: 0, gap: spacing.xs },
  tenderInput: { height: fieldHeight, minHeight: fieldHeight, borderColor: colors.lineStrong },
  changeBox: {
    height: fieldHeight,
    minHeight: fieldHeight,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceContainerLow,
    justifyContent: "flex-end",
    alignItems: "center",
    gap: spacing.xs,
  },
  changeBoxReady: { backgroundColor: colors.successSoft },
  changeValue: { fontWeight: "700" },
  shortageValue: { color: colors.danger },
  displayLabel: {
    color: colors.inkSubtle,
    fontSize: type.overline,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  keypadGrid: { flex: 1, minHeight: 0, gap: spacing.sm },
  keypadGridStacked: { flex: 0, flexGrow: 0, flexShrink: 0, flexBasis: "auto", minHeight: 0 },
  keypadRow: {
    flex: 1,
    minHeight: 48,
    flexDirection: "row",
    alignItems: "stretch",
    position: "relative",
    marginHorizontal: -spacing.xs,
  },
  keypadRowStacked: { flex: 0, flexGrow: 0, flexShrink: 0, flexBasis: "auto", minHeight: 48 },
  keypadRowMobile: { height: 48, minHeight: 48 },
  keypadCell: {
    flexGrow: 1,
    flexBasis: 0,
    minWidth: 0,
    paddingHorizontal: spacing.xs,
  },
  keypadButton: {
    flex: 1,
    minWidth: 0,
    minHeight: 48,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
  },
  keypadText: { color: colors.ink, fontSize: type.amount, lineHeight: 25, fontWeight: "500" },
  keypadTextMobile: { fontSize: type.amount, lineHeight: 25 },
  keypadClear: { borderColor: "#FECACA", backgroundColor: "#FFF7F7" },
  keypadClearText: { color: colors.danger },
  applyButton: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    right: spacing.xs,
    marginLeft: spacing.xs,
    minHeight: 48,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  applyButtonText: { color: colors.white, ...typography.button },
  applyButtonTextTablet: { fontSize: type.button, lineHeight: 18 },
  disabledButton: { opacity: 0.5 },
  qrisPanel: { flex: 1, minHeight: 0 },
  qrisPanelStacked: { flex: 0, minHeight: 0 },
  verifyBox: {
    flex: 1,
    minHeight: 290,
    padding: 20,
    backgroundColor: colors.tintYellow,
    borderWidth: 1,
    borderColor: colors.tintYellowBold,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  verifyBoxStacked: { flex: 0, flexGrow: 0, flexShrink: 0, flexBasis: "auto" },
  verifyIcon: {
    width: 48,
    height: 48,
    borderRadius: 48,
    backgroundColor: colors.tintYellowBold,
    alignItems: "center",
    justifyContent: "center",
  },
  verifyTitle: {
    color: colors.ink,
    ...typography.sectionTitle,
    textAlign: "center",
  },
  verifyDescription: {
    color: colors.inkMuted,
    ...typography.description,
    textAlign: "center",
    maxWidth: 420,
  },
  verifyAmount: { color: colors.ink, fontWeight: "700" },
  verifyButton: {
    minHeight: 46,
    paddingHorizontal: 18,
    borderRadius: radius.md,
    backgroundColor: colors.tintYellowBold,
    borderWidth: 1,
    borderColor: "#F59E0B",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 7,
  },
  verifyButtonDone: {
    backgroundColor: colors.successSoft,
    borderColor: colors.success,
  },
  verifyButtonText: { color: "#B45309", ...typography.button },
});
