import { StyleSheet } from "react-native";
import { colors, elevation, radius, spacing } from "../../../theme";

export const screenStyles = StyleSheet.create({
  page: { gap: spacing.md },
  pageFill: { flex: 1, minHeight: 0 },
  paymentLayout: {
    flex: 1,
    minHeight: 0,
    alignItems: "stretch",
    gap: spacing.md,
  },
  paymentLayoutStack: { flexDirection: "column" },
  paymentColumn: { flex: 1.15, gap: spacing.md, minWidth: 0, minHeight: 0 },
  receiptColumn: { flex: 0.85, gap: spacing.md, minWidth: 0, minHeight: 0 },
  billBar: { minHeight: 92, justifyContent: "center" },
  billSummary: { gap: 5 },
  billHeader: { alignItems: "center", gap: 8 },
  billAmountRow: {
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  billOrderCount: { alignItems: "flex-end", paddingBottom: 3 },
  billOrderCountLabel: {
    color: "#64748B",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  billOrderCountLabelAdaptive: { fontSize: 11 },
  billOrderCountLabelTablet: { fontSize: 12 },
  billOrderCountValue: { color: colors.ink, fontSize: 12, fontWeight: "800" },
  microLabel: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
  },
  billOrderTag: {
    color: colors.primary,
    backgroundColor: colors.surfaceTint,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    borderRadius: 5,
    paddingHorizontal: 7,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: "900",
  },
  billTotal: {
    color: colors.success,
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "900",
  },
  billTotalMobile: { fontSize: 26, lineHeight: 30 },
  billTotalTablet: { fontSize: 28, lineHeight: 32 },
  microLabelAdaptive: { fontSize: 11 },
  microLabelTablet: { fontSize: 12 },
  methodSelector: {
    padding: 5,
    borderRadius: radius.pill,
    backgroundColor: "#E5E7EB",
    gap: 5,
  },
  methodButton: {
    flex: 1,
    minHeight: 56,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 9,
  },
  methodButtonActive: { backgroundColor: colors.primary, ...elevation.button },
  methodIcon: {
    width: 34,
    height: 34,
    borderRadius: 34,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  methodIconActive: { backgroundColor: "rgba(255,255,255,0.2)" },
  methodTitle: { color: colors.inkMuted, fontSize: 12, fontWeight: "800" },
  methodTitleActive: { color: colors.white },
  primaryButton: {
    minHeight: 52,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    ...elevation.button,
  },
  primaryButtonText: { color: colors.white, fontSize: 13, fontWeight: "900" },
});
