import { StyleSheet } from "react-native";
import {
  colors,
  elevation,
  radius,
  spacing,
  type,
  typography,
} from "../../../theme";

export const screenStyles = StyleSheet.create({
  page: { gap: spacing.md },
  pageFill: { flex: 1, minHeight: 0 },
  paymentLayout: {
    flex: 1,
    minHeight: 0,
    alignItems: "stretch",
    gap: spacing.md,
  },
  paymentLayoutStack: {
    flex: 0,
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    flexDirection: "column",
  },
  paymentColumn: { flex: 1.15, gap: spacing.md, minWidth: 0, minHeight: 0 },
  paymentColumnStacked: { flex: 0, minHeight: 0 },
  receiptColumn: { flex: 0.85, gap: spacing.md, minWidth: 0, minHeight: 0 },
  receiptColumnStacked: { flex: 0, minHeight: 0 },
  billBar: { minHeight: 92, justifyContent: "center" },
  billSummary: { gap: 5 },
  billHeader: { alignItems: "center", gap: 8 },
  billAmountRow: {
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  billOrderCount: { alignItems: "flex-end", paddingBottom: 3 },
  billOrderCountLabel: {
    color: colors.inkSubtle,
    fontSize: type.micro,
    fontWeight: "700",
    letterSpacing: 0.6,
  },
  billOrderCountLabelAdaptive: { fontSize: type.micro },
  billOrderCountLabelTablet: { fontSize: type.micro },
  billOrderCountValue: { color: colors.ink, fontSize: type.micro, fontWeight: "600" },
  microLabel: {
    color: colors.inkSubtle,
    fontSize: type.micro,
    fontWeight: "700",
    letterSpacing: 1,
  },
  billOrderTag: {
    color: colors.primary,
    backgroundColor: colors.surfaceTint,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.sm,
    paddingHorizontal: 7,
    paddingVertical: 3,
    fontSize: type.micro,
    fontWeight: "700",
  },
  billTotal: {
    color: colors.ink,
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "700",
  },
  billTotalMobile: { fontSize: 26, lineHeight: 30 },
  billTotalTablet: { fontSize: 28, lineHeight: 32 },
  microLabelAdaptive: { fontSize: type.micro },
  microLabelTablet: { fontSize: type.micro },
  methodSelector: {
    padding: 5,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceContainerLow,
    gap: 5,
  },
  methodButton: {
    flex: 1,
    minHeight: 56,
    paddingHorizontal: 10,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 9,
  },
  methodButtonActive: { backgroundColor: colors.primary, ...elevation.button },
  methodIcon: {
    width: 34,
    height: 34,
    borderRadius: 34,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
  },
  methodIconActive: { backgroundColor: "rgba(255,255,255,0.2)" },
  methodTitle: { color: colors.inkMuted, ...typography.button },
  methodTitleActive: { color: colors.white },
  primaryButton: {
    minHeight: 52,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    ...elevation.button,
  },
  primaryButtonText: { color: colors.white, ...typography.button },
  registerClosedContent: { alignItems: "center", gap: spacing.md },
  registerClosedIcon: {
    width: 62,
    height: 62,
    borderRadius: radius.pill,
    backgroundColor: colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  registerClosedCopy: { width: "100%", alignItems: "center", gap: spacing.xs },
  registerClosedTitle: {
    color: colors.ink,
    ...typography.sectionTitle,
    textAlign: "center",
  },
  registerClosedDescription: {
    width: "100%",
    maxWidth: 760,
    color: colors.inkMuted,
    ...typography.description,
    textAlign: "center",
  },
  registerClosedAction: { width: "100%" },
});
