import { StyleSheet } from "react-native";
import { colors, elevation, radius, spacing } from "../../theme";

export const styles = StyleSheet.create({
  shell: { flex: 1, backgroundColor: colors.canvas },
  topBar: {
    height: 64,
    paddingHorizontal: 20,
    alignItems: "center",
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  brandBlock: { flex: 1, alignItems: "center", gap: 10, minWidth: 0 },
  brandLogo: { width: 34, height: 34, borderRadius: 10 },
  brandText: { gap: 0, minWidth: 132 },
  brandName: { color: colors.ink, fontSize: 14, fontWeight: "800" },
  brandSub: { color: colors.inkMuted, fontSize: 10, fontWeight: "500" },
  headerSeparator: { width: 1, height: 30, backgroundColor: colors.line },
  cashierPill: {
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceContainerLow,
  },
  cashierText: { color: colors.inkMuted, fontSize: 11, fontWeight: "700" },
  greenDot: {
    width: 7,
    height: 7,
    borderRadius: 7,
    backgroundColor: colors.success,
  },
  headerRight: { alignItems: "center", gap: 14 },
  printerPill: {
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: radius.pill,
    backgroundColor: colors.successSoft,
  },
  printerText: { color: "#15803D", fontSize: 10, fontWeight: "800" },
  closeShiftPill: {
    backgroundColor: colors.dangerSoft,
    flexDirection: "row",
    flexShrink: 0,
  },
  closeShiftText: { color: colors.danger, fontSize: 10, fontWeight: "800" },
  clockBlock: { alignItems: "flex-end", gap: 0 },
  clock: { color: colors.ink, fontSize: 12, fontWeight: "800" },
  date: { color: colors.inkMuted, fontSize: 10 },
  headerIcon: {
    width: 40,
    height: 40,
    borderRadius: 40,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  notificationCountBadge: {
    position: "absolute",
    top: 0,
    right: -2,
    minWidth: 17,
    height: 17,
    paddingHorizontal: 3,
    borderRadius: 9,
    backgroundColor: colors.primary,
    borderWidth: 1,
    borderColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationCountText: {
    color: colors.white,
    fontSize: 8,
    lineHeight: 11,
    fontWeight: "900",
  },
  notificationDropdown: {
    padding: 0,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    ...elevation.panel,
  },
  notificationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  notificationHeading: { color: colors.ink, fontSize: 13, fontWeight: "900" },
  notificationUnreadCount: {
    color: colors.inkMuted,
    fontSize: 9,
    fontWeight: "700",
  },
  notificationBody: { padding: 0 },
  notificationList: { paddingHorizontal: spacing.md, paddingBottom: spacing.xs },
  notificationRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.xs,
    paddingVertical: spacing.sm,
  },
  notificationRowBorder: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  notificationBulletTarget: {
    width: 20,
    height: 20,
    marginTop: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationUnreadBullet: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  notificationBulletSpace: { width: 20, height: 20, marginTop: 1 },
  notificationCopy: { flex: 1, minWidth: 0, gap: 2 },
  notificationTitle: { color: colors.ink, fontSize: 11, fontWeight: "800" },
  notificationMessage: {
    color: colors.inkMuted,
    fontSize: 10,
    lineHeight: 14,
  },
  notificationTime: { color: colors.inkSubtle, fontSize: 9, fontWeight: "600" },
  notificationEmpty: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
    color: colors.inkMuted,
    fontSize: 11,
    textAlign: "center",
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 34,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  profileDropdown: {
    width: 220,
    padding: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    ...elevation.panel,
  },
  profileDropdownHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.xs,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },
  profileDropdownAvatar: {
    width: 32,
    height: 32,
    borderRadius: 32,
    flexShrink: 0,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  profileDropdownIdentity: { flex: 1, minWidth: 0, gap: 1 },
  profileDropdownName: { color: colors.ink, fontSize: 12, fontWeight: "900" },
  profileDropdownRole: {
    color: colors.inkMuted,
    fontSize: 10,
    fontWeight: "600",
  },
  profileDropdownBody: { padding: 0 },
  logoutButton: {
    minHeight: 36,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.sm,
    backgroundColor: colors.dangerSoft,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  logoutText: { color: colors.danger, fontSize: 11, fontWeight: "900" },
  avatarText: { color: colors.white, fontSize: 11, fontWeight: "800" },
  body: { flex: 1, alignItems: "stretch" },
  sidebar: {
    backgroundColor: colors.surfaceContainerLow,
    paddingHorizontal: 10,
    paddingTop: 16,
    paddingBottom: 16,
    justifyContent: "space-between",
  },
  sideNav: { gap: 8 },
  navItem: {
    minHeight: 60,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    position: "relative",
  },
  navItemActive: { backgroundColor: colors.primary },
  navIconWrap: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  navLabel: {
    color: colors.inkMuted,
    fontSize: 10,
    fontWeight: "800",
    textAlign: "center",
  },
  navLabelActive: { color: colors.white },
  queueBadge: {
    position: "absolute",
    top: -7,
    right: -12,
    minWidth: 16,
    height: 16,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: colors.warning,
    alignItems: "center",
    justifyContent: "center",
  },
  queueBadgeText: { color: colors.white, fontSize: 9, fontWeight: "900" },
  closeShiftModal: {
    width: "100%",
    maxWidth: 440,
    padding: spacing.lg,
    borderRadius: radius.xl,
    backgroundColor: colors.white,
  },
  closeShiftModalHeader: {
    width: "100%",
    alignItems: "center",
    gap: spacing.md,
    paddingBottom: spacing.sm,
  },
  closeShiftModalIcon: {
    width: 44,
    height: 44,
    borderRadius: 44,
    backgroundColor: colors.dangerSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  closeShiftModalHeading: { flex: 1, minWidth: 0, gap: 3 },
  closeShiftModalTitle: { color: colors.ink, fontSize: 17, fontWeight: "900" },
  closeShiftModalSubtitle: { color: colors.inkMuted, fontSize: 11 },
  closeShiftModalCopy: {
    color: colors.inkMuted,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  closeShiftCashSummary: {
    marginTop: spacing.md,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceContainerLow,
    gap: spacing.sm,
  },
  closeShiftCashRow: { alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  closeShiftCashLabel: { color: colors.inkMuted, fontSize: 11 },
  closeShiftCashValue: { color: colors.ink, fontSize: 11, fontWeight: "800" },
  closeShiftCashTotalLabel: { color: colors.ink, fontSize: 11, fontWeight: "800" },
  closeShiftCashTotal: { color: colors.success, fontSize: 13, fontWeight: "900" },
  closeShiftCountLabel: {
    marginTop: spacing.md,
    marginBottom: spacing.xs,
    color: colors.inkMuted,
    fontSize: 10,
    fontWeight: "900",
  },
  closeShiftCountInput: {
    minHeight: 48,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  closeShiftCountPrefix: { color: colors.success, fontSize: 13, fontWeight: "900" },
  closeShiftCountField: { flex: 1, minWidth: 0, paddingVertical: 0, fontSize: 13, color: colors.ink },
  closeShiftDifference: { marginTop: spacing.xs, color: colors.inkMuted, fontSize: 11, textAlign: "right" },
  closeShiftModalFooter: {
    width: "100%",
    alignItems: "stretch",
    paddingTop: spacing.md,
  },
  closeShiftConfirmButton: {
    width: "100%",
    minHeight: 48,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.pill,
    backgroundColor: colors.danger,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  closeShiftConfirmDisabled: { opacity: 0.5 },
  closeShiftConfirmText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "800",
  },
  onlinePill: {
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 7,
    borderRadius: radius.pill,
    backgroundColor: colors.successSoft,
  },
  onlineText: { color: "#15803D", fontSize: 10, fontWeight: "800" },
  onlinePillBlue: { backgroundColor: colors.surfaceTint },
  onlineTextBlue: { color: colors.primary },
  blueDot: { backgroundColor: colors.primary },
  scroll: { flex: 1 },
  content: { gap: spacing.xxl },
  contentStatic: { flex: 1, minWidth: 0, minHeight: 0 },
});
