import { StyleSheet } from "react-native";
import {
  colors,
  elevation,
  fieldHeight,
  radius,
  spacing,
  type,
  typography,
} from "../../theme";

export const styles = StyleSheet.create({
  shell: { flex: 1, backgroundColor: colors.canvas },
  topBar: {
    height: 64,
    paddingHorizontal: 20,
    alignItems: "center",
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  topBarMobile: { height: 56, paddingHorizontal: spacing.sm },
  brandBlock: { flex: 1, alignItems: "center", gap: 10, minWidth: 0 },
  brandLogo: { width: 34, height: 34, borderRadius: radius.md },
  brandText: { gap: 0, minWidth: 132 },
  brandName: { color: colors.ink, fontSize: type.bodySmall, fontWeight: "600" },
  brandSub: { color: colors.inkMuted, fontSize: type.micro, fontWeight: "500" },
  headerSeparator: { width: 1, height: 30, backgroundColor: colors.line },
  cashierPill: {
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceContainerLow,
  },
  cashierText: { color: colors.inkMuted, fontSize: type.micro, lineHeight: 17, fontWeight: "600" },
  greenDot: {
    width: 7,
    height: 7,
    borderRadius: 7,
    backgroundColor: colors.success,
  },
  headerRight: { alignItems: "center", gap: spacing.sm },
  headerUtilityActions: { alignItems: "center", gap: spacing.xs },
  headerCashAction: {
    minHeight: 34,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceTint,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: spacing.xs,
  },
  headerCashActionCompact: {
    width: 36,
    height: 36,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceTint,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCashActionMobileLabeled: {
    minHeight: 36,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceTint,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 4,
  },
  headerCashActionClose: { backgroundColor: colors.dangerSoft },
  headerCashActionDisabled: { backgroundColor: colors.surfaceContainerLow, opacity: 0.7 },
  headerCashActionText: { color: colors.primary, fontSize: type.micro, fontWeight: "600" },
  headerCashActionCloseText: { color: colors.danger },
  headerCashActionDisabledText: { color: colors.inkSubtle },
  printerPill: {
    minHeight: 32,
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
    paddingHorizontal: 9,
    borderRadius: radius.md,
    backgroundColor: colors.successSoft,
  },
  printerText: { color: colors.inkMuted, fontSize: type.micro, lineHeight: 17, fontWeight: "600" },
  clockBlock: { alignItems: "flex-end", gap: 0 },
  clock: { color: colors.ink, fontSize: type.micro, fontWeight: "600" },
  date: { color: colors.inkMuted, fontSize: type.micro },
  headerIcon: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  notificationCountBadge: {
    position: "absolute",
    top: 0,
    right: -2,
    minWidth: 17,
    height: 17,
    paddingHorizontal: 3,
    borderRadius: radius.sm,
    backgroundColor: colors.primary,
    borderWidth: 1,
    borderColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationCountText: {
    color: colors.white,
    fontSize: type.micro,
    lineHeight: 14,
    fontWeight: "600",
  },
  notificationDropdown: {
    padding: 0,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    ...elevation.panel,
  },
  notificationHeader: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.xs,
  },
  notificationHeading: { color: colors.ink, ...typography.label },
  notificationUnreadCount: {
    color: colors.inkMuted,
    fontSize: type.micro,
    lineHeight: 17,
    fontWeight: "600",
  },
  notificationBody: { padding: 0 },
  notificationList: { paddingHorizontal: spacing.md, paddingBottom: spacing.xs },
  notificationMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
  },
  notificationMarkAllButton: {
    minHeight: 24,
    justifyContent: "center",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceTint,
  },
  notificationMarkAllText: { color: colors.primary, ...typography.compactButton },
  notificationRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.xs,
    paddingVertical: spacing.sm,
  },
  notificationRowBorder: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  notificationBulletTarget: {
    width: 20,
    height: 20,
    marginTop: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationUnreadBullet: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  notificationBulletSpace: { width: 20, height: 20, marginTop: 1 },
  notificationCopy: { flex: 1, minWidth: 0, gap: 2 },
  notificationTitle: { color: colors.ink, fontSize: type.label, lineHeight: 18, fontWeight: "600" },
  notificationMessage: {
    color: colors.inkMuted,
    ...typography.helper,
  },
  notificationTime: { color: colors.inkSubtle, fontSize: type.micro, lineHeight: 17, fontWeight: "500" },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 34,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  profileDropdown: {
    width: 240,
    padding: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    ...elevation.panel,
  },
  profileDropdownHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    paddingHorizontal: spacing.xs,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },
  profileDropdownAvatar: {
    width: 32,
    height: 32,
    borderRadius: 32,
    flexShrink: 0,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  profileDropdownIdentity: { flex: 1, minWidth: 0, gap: 1 },
  profileDropdownClock: { alignItems: "flex-end", flexShrink: 0 },
  profileDropdownName: { color: colors.ink, fontSize: type.label, lineHeight: 18, fontWeight: "600" },
  profileDropdownRole: {
    color: colors.inkMuted,
    fontSize: type.micro,
    fontWeight: "600",
  },
  profileDropdownBody: { padding: 0 },
  profileDropdownActions: { gap: spacing.xs },
  logoutButton: {
    width: "100%",
    minHeight: 40,
    paddingHorizontal: 9,
    borderRadius: radius.md,
    backgroundColor: colors.dangerSoft,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  logoutText: { color: colors.danger, fontSize: type.micro, lineHeight: 17, fontWeight: "600" },
  avatarText: { color: colors.white, fontSize: type.micro, fontWeight: "600" },
  body: { flex: 1, alignItems: "stretch" },
  mobileNav: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "stretch",
    paddingHorizontal: spacing.xs,
    paddingTop: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.white,
  },
  mobileNavItem: {
    flex: 1,
    minWidth: 0,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    paddingHorizontal: 2,
  },
  mobileNavIconWrap: {
    width: 42,
    height: 25,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  mobileNavIconWrapActive: { backgroundColor: colors.surfaceTint },
  mobileNavLabel: {
    color: colors.inkMuted,
    fontSize: type.micro,
    fontWeight: "600",
    textAlign: "center",
  },
  mobileNavLabelActive: { color: colors.primaryDark, fontWeight: "600" },
  mobileQueueBadge: {
    position: "absolute",
    top: -5,
    right: 4,
    minWidth: 15,
    height: 15,
    borderRadius: radius.sm,
    paddingHorizontal: 3,
    backgroundColor: colors.warning,
    alignItems: "center",
    justifyContent: "center",
  },
  sidebar: {
    backgroundColor: colors.surface,
    borderRightWidth: 1,
    borderRightColor: colors.line,
    paddingHorizontal: 10,
    paddingTop: 16,
    paddingBottom: 16,
    justifyContent: "space-between",
  },
  sideNav: { gap: 8 },
  navItem: {
    minHeight: 60,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    position: "relative",
  },
  navItemActive: { backgroundColor: colors.surfaceTint },
  navIconWrap: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  navLabel: {
    color: colors.inkMuted,
    fontSize: type.micro,
    fontWeight: "600",
    textAlign: "center",
  },
  navLabelActive: { color: colors.primaryDark },
  queueBadge: {
    position: "absolute",
    top: -7,
    right: -12,
    minWidth: 16,
    height: 16,
    borderRadius: radius.sm,
    paddingHorizontal: 4,
    backgroundColor: colors.warning,
    alignItems: "center",
    justifyContent: "center",
  },
  queueBadgeText: { color: colors.white, fontSize: type.micro, lineHeight: 14, fontWeight: "600" },
  closeShiftModal: {
    width: "94%",
    maxWidth: 440,
    padding: spacing.lg,
    borderRadius: 18,
    backgroundColor: colors.white,
  },
  closeShiftModalHeader: {
    width: "100%",
    alignItems: "center",
    gap: spacing.sm,
    paddingBottom: spacing.sm,
  },
  closeShiftModalIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: colors.dangerSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  closeShiftModalHeading: { flex: 1, minWidth: 0 },
  closeShiftModalTitle: { color: colors.ink, fontSize: 18, lineHeight: 23, fontWeight: "600" },
  closeShiftDismissButton: { width: 40, height: 40, borderRadius: radius.md },
  closeShiftModalCopy: {
    marginBottom: spacing.md,
    color: colors.inkMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  closeShiftCashSummary: {
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceContainerLow,
    gap: spacing.xs,
  },
  closeShiftCashRow: { minHeight: 20, alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  closeShiftCashLabel: { flex: 1, color: colors.inkMuted, fontSize: 13, lineHeight: 18 },
  closeShiftCashValue: { color: colors.ink, fontSize: 13, lineHeight: 18, fontWeight: "500", fontVariant: ["tabular-nums"] },
  closeShiftCashTotalLabel: { flex: 1, color: colors.ink, fontSize: 13, lineHeight: 18, fontWeight: "600" },
  closeShiftCashTotal: { color: colors.success, fontSize: 14, lineHeight: 19, fontWeight: "600", fontVariant: ["tabular-nums"] },
  closeShiftQueueNotice: {
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.tintCream,
  },
  closeShiftQueueNoticeActive: { backgroundColor: colors.dangerSoft },
  closeShiftQueueNoticeText: { flex: 1, minWidth: 0, color: colors.danger, fontSize: 12, lineHeight: 16, fontWeight: "500" },
  closeShiftQueueLink: { minHeight: 32, flexDirection: "row", alignItems: "center", gap: spacing.xs },
  closeShiftQueueLinkText: { color: colors.danger, fontSize: 11, lineHeight: 16, fontWeight: "600" },
  closeShiftCountHeading: { marginTop: spacing.md, marginBottom: spacing.xs, justifyContent: "space-between", alignItems: "center", gap: spacing.sm },
  closeShiftCountLabel: {
    color: colors.inkMuted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
  },
  closeShiftCountInput: {
    minHeight: fieldHeight,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.lineStrong,
    borderRadius: radius.md,
    backgroundColor: colors.canvas,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  closeShiftCountPrefix: { color: colors.primary, ...typography.input, fontWeight: "600" },
  closeShiftCountField: { flex: 1, minWidth: 0, paddingVertical: 0, fontSize: 15, lineHeight: 21, color: colors.ink, fontVariant: ["tabular-nums"] },
  closeShiftDifference: { ...typography.helper, fontWeight: "600", textAlign: "right" },
  closeShiftDifferenceMatch: { color: colors.success },
  closeShiftDifferenceMismatch: { color: colors.danger },
  closeShiftModalFooter: {
    width: "100%",
    alignItems: "stretch",
    paddingTop: spacing.md,
  },
  closeShiftConfirmButton: {
    width: "100%",
    minHeight: 44,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.danger,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  closeShiftConfirmDisabled: { backgroundColor: colors.line },
  closeShiftConfirmText: { color: colors.white, ...typography.button },
  closeShiftConfirmDisabledText: { color: colors.inkMuted },
  onlinePill: {
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 7,
    borderRadius: radius.md,
    backgroundColor: colors.successSoft,
  },
  onlineText: { color: "#15803D", fontSize: type.micro, fontWeight: "600" },
  onlinePillBlue: { backgroundColor: colors.surfaceTint },
  onlineTextBlue: { color: colors.primary },
  blueDot: { backgroundColor: colors.primary },
  scroll: { flex: 1 },
  content: { gap: spacing.xxl },
  contentStatic: { flex: 1, minWidth: 0, minHeight: 0 },
});
