import { StyleSheet } from "react-native";
import { colors, elevation, radius, spacing, type } from "../../theme";

export const dateRangePickerStyles = StyleSheet.create({
  modal: {
    width: 420,
    maxWidth: "92%",
    borderRadius: radius.xl,
    padding: spacing.lg,
    backgroundColor: colors.white,
    ...elevation.panel,
  },
  header: {
    width: "100%",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: 0,
  },
  heading: { flex: 1, minWidth: 0, gap: 3 },
  title: { color: colors.ink, fontSize: type.section, lineHeight: 24, fontWeight: "900" },
  subtitle: { color: colors.inkMuted, fontSize: 12 },
  body: { minHeight: 0, paddingHorizontal: 0, paddingTop: spacing.sm },
  scroll: { flexGrow: 0, minHeight: 0 },
  scrollContent: { gap: spacing.md, paddingVertical: spacing.xs },
  selectedRange: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceTint,
    gap: 3,
  },
  selectedLabel: { color: colors.inkSubtle, fontSize: 12, fontWeight: "800" },
  selectedText: { color: colors.primary, fontSize: 12, fontWeight: "900" },
  monthHeader: { alignItems: "center", justifyContent: "space-between" },
  monthTitle: { color: colors.ink, fontSize: 13, fontWeight: "900" },
  monthTitleButton: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
    borderRadius: radius.md,
  },
  monthButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.pill,
  },
  yearGrid: { width: "100%", flexDirection: "row", flexWrap: "wrap" },
  yearCell: { width: "25%", height: 44, padding: 2 },
  monthGrid: { width: "100%", flexDirection: "row", flexWrap: "wrap" },
  monthCell: { width: `${100 / 3}%`, height: 48, padding: 2 },
  selectorOption: {
    flex: 1,
    minHeight: 40,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
  },
  selectorOptionSelected: { backgroundColor: colors.primary },
  selectorOptionText: { color: colors.ink, fontSize: 12, fontWeight: "700" },
  selectorOptionTextSelected: { color: colors.white, fontWeight: "900" },
  weekdayRow: { flexDirection: "row", width: "100%" },
  weekday: {
    width: `${100 / 7}%`,
    color: colors.inkSubtle,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "800",
  },
  dayGrid: { width: "100%", flexDirection: "row", flexWrap: "wrap" },
  dayCell: {
    width: `${100 / 7}%`,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  dayButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.pill,
  },
  dayButtonInRange: { backgroundColor: colors.surfaceTint },
  dayButtonSelected: { backgroundColor: colors.primary },
  dayText: { color: colors.ink, fontSize: 12, fontWeight: "700" },
  dayTextSelected: { color: colors.white, fontWeight: "900" },
  footer: {
    width: "100%",
    alignItems: "stretch",
    paddingHorizontal: 0,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  applyButton: {
    width: "100%",
    minHeight: 44,
    paddingHorizontal: spacing.md,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  applyButtonDisabled: { opacity: 0.5 },
  applyText: { color: colors.white, fontSize: 12, fontWeight: "900" },
});
