import { StyleSheet } from "react-native";
import {
  colors,
  elevation,
  fieldHeight,
  radius,
  spacing,
  type,
  typography,
} from "../../../theme";

export const styles = StyleSheet.create({
  page: { width: "100%", gap: spacing.lg, paddingBottom: spacing.xxl },
  pageHeader: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.lg,
  },
  pageHeaderCompact: { alignItems: "stretch", flexDirection: "column" },
  pageHeading: { flex: 1, minWidth: 0, gap: spacing.xs },
  pageTitle: { color: colors.ink, ...typography.pageTitle },
  pageDescription: { color: colors.inkMuted, ...typography.description },
  pageActions: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-end", gap: spacing.sm },
  pageActionsCompact: { width: "100%", alignItems: "center", justifyContent: "space-between", flexDirection: "row", flexWrap: "wrap" },
  pageActionsPhone: { alignItems: "stretch", flexDirection: "column" },
  primaryButton: { minHeight: 44, paddingHorizontal: spacing.lg, borderRadius: radius.md, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.sm, ...elevation.button },
  primaryButtonFull: { width: "100%" },
  primaryButtonText: { color: colors.white, ...typography.button },

  summaryRow: { width: "100%", flexDirection: "row", gap: spacing.md },
  summaryColumn: { flexDirection: "column" },
  summaryCard: { flex: 1, minWidth: 0, gap: spacing.md },
  summaryTop: { alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  summaryLabel: { color: colors.inkSubtle, fontSize: type.overline, lineHeight: 15, fontWeight: "600", letterSpacing: 0.7, textTransform: "uppercase" },
  summaryCount: { paddingHorizontal: spacing.sm, paddingVertical: 4, borderRadius: radius.sm, backgroundColor: colors.surfaceTint, borderWidth: 1, borderColor: colors.surfaceBlue, color: colors.primary, fontSize: type.micro, fontWeight: "600" },
  summaryCountOperational: { backgroundColor: colors.tintYellow, borderColor: colors.tintYellowBold, color: "#B45309" },
  summaryAmount: { color: colors.ink, fontSize: type.numeric, lineHeight: 32, fontWeight: "700", fontVariant: ["tabular-nums"] },
  summaryHint: { color: colors.inkSubtle, ...typography.helper },

  registerSummary: { width: "100%", gap: spacing.lg },
  registerSummaryHeader: { alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  registerSummaryCopy: { flex: 1, minWidth: 0, gap: spacing.xs },
  registerStatusLine: { alignItems: "center", gap: spacing.xs },
  registerStatusDot: { width: 8, height: 8, borderRadius: radius.pill },
  registerSummaryTitle: { color: colors.ink, fontSize: type.bodySmall, lineHeight: 21, fontWeight: "600" },
  registerSummaryDescription: { color: colors.inkMuted, ...typography.description },
  registerExpected: { alignItems: "flex-end", gap: spacing.xs },
  registerExpectedLabel: { color: colors.inkMuted, fontSize: type.overline, lineHeight: 15, fontWeight: "600", letterSpacing: 0.7 },
  registerExpectedValue: { color: colors.ink, fontSize: type.numeric, lineHeight: 32, fontWeight: "700", fontVariant: ["tabular-nums"] },
  registerBreakdown: { paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.line, flexWrap: "wrap", gap: spacing.lg },
  registerBreakdownItem: { minWidth: 118, flex: 1, gap: spacing.xs },
  registerBreakdownLabel: { color: colors.inkMuted, ...typography.helper },
  registerBreakdownValue: { color: colors.ink, fontSize: type.bodySmall, lineHeight: 21, fontWeight: "600", fontVariant: ["tabular-nums"] },
  closedRegisterReport: { alignItems: "center", justifyContent: "space-between", paddingTop: spacing.sm, borderTopWidth: 1, borderTopColor: colors.line },
  registerBalanced: { color: colors.success },
  registerMismatch: { color: colors.danger },

  searchInputFilter: { width: "100%" },
  searchText: { ...typography.input },

  tableDate: { color: colors.inkMuted, fontSize: type.caption, lineHeight: 18 },
  transactionDescription: { color: colors.ink, fontSize: type.label, lineHeight: 18, fontWeight: "600" },
  transactionDetail: { color: colors.inkSubtle, ...typography.helper },
  categoryBadge: { minHeight: 22, paddingHorizontal: spacing.sm, borderRadius: radius.sm, backgroundColor: colors.surfaceTint, borderWidth: 1, borderColor: colors.surfaceBlue, alignItems: "center", alignSelf: "flex-start", justifyContent: "center" },
  categoryBadgeOperational: { backgroundColor: colors.surfaceContainerLow, borderColor: colors.line },
  categoryText: { color: colors.primaryDark, fontSize: type.micro, lineHeight: 17, fontWeight: "600" },
  categoryTextOperational: { color: colors.inkMuted },
  amountText: { color: colors.ink, fontSize: type.label, fontWeight: "700", fontVariant: ["tabular-nums"] },


  modal: { width: "94%", maxWidth: 560, borderRadius: radius.lg, backgroundColor: colors.white, overflow: "hidden", ...elevation.panel },
  modalHeader: { alignItems: "center", gap: spacing.md, padding: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.line },
  modalIcon: { width: 38, height: 38, borderRadius: radius.md, backgroundColor: colors.surfaceTint, alignItems: "center", justifyContent: "center" },
  modalHeading: { flex: 1, minWidth: 0, gap: spacing.xs },
  modalTitle: { color: colors.ink, ...typography.sectionTitle },
  modalSubtitle: { color: colors.inkMuted, ...typography.description },
  modalBody: { minHeight: 0, padding: 0 },
  modalScroll: { minHeight: 0 },
  modalForm: { padding: spacing.lg, gap: spacing.md },
  formGroup: { gap: spacing.sm },
  formLabel: { color: colors.ink, ...typography.label },
  formInput: { width: "100%" },
  amountInput: { fontVariant: ["tabular-nums"] },
  inputPrefix: { color: colors.inkMuted, ...typography.input, fontWeight: "600" },
  formError: { color: colors.danger, ...typography.helper, fontWeight: "600" },
  dateTimeRow: { alignItems: "center", gap: spacing.sm },
  dateButton: { flex: 1, minWidth: 0, minHeight: fieldHeight, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.lineStrong, borderRadius: radius.md, backgroundColor: colors.canvas, alignItems: "center", flexDirection: "row", gap: spacing.sm },
  dateButtonText: { flex: 1, color: colors.ink, ...typography.input, fontWeight: "500" },
  timeInput: { width: 112, minHeight: fieldHeight },
  fundingRow: { flexDirection: "row", gap: spacing.sm },
  fundingButton: { flex: 1, minHeight: 48, paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.xs },
  fundingButtonActive: { borderColor: colors.primary, backgroundColor: colors.surfaceTint },
  fundingText: { color: colors.inkMuted, ...typography.compactButton },
  fundingTextActive: { color: colors.primary, fontWeight: "600" },
  formHint: { color: colors.inkSubtle, ...typography.helper },
  modalFooter: { width: "100%", padding: spacing.lg, borderTopWidth: 1, borderTopColor: colors.line },
  saveButton: { width: "100%", minHeight: 48, borderRadius: radius.md, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" },
  saveButtonDisabled: { opacity: 0.45 },
  saveButtonText: { color: colors.white, ...typography.button },
  cancelButton: { width: "100%", minHeight: 42, marginTop: spacing.xs, alignItems: "center", justifyContent: "center" },
  cancelButtonText: { color: colors.inkMuted, ...typography.button },

  detailRows: { padding: spacing.lg, gap: spacing.md },
  detailLine: { alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md },
  detailLabel: { color: colors.inkSubtle, fontSize: type.caption },
  detailValue: { maxWidth: "65%", color: colors.ink, fontSize: type.caption, fontWeight: "700", textAlign: "right" },
  detailAmount: { color: colors.ink, fontSize: type.body, fontWeight: "700", fontVariant: ["tabular-nums"] },
  detailDivider: { height: 1, backgroundColor: colors.line },
});
