import { StyleSheet } from "react-native";
import { colors, elevation, radius, spacing, type } from "../../../theme";

export const styles = StyleSheet.create({
  page: { width: "100%", gap: spacing.lg, paddingBottom: spacing.xxl },
  pageHeader: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.lg,
  },
  pageHeaderCompact: { alignItems: "stretch", flexDirection: "column" },
  pageHeading: { flex: 1, minWidth: 0, gap: spacing.xs },
  pageTitle: { color: colors.ink, fontSize: type.title, lineHeight: 28, fontWeight: "900" },
  pageDescription: { color: colors.inkMuted, fontSize: type.bodySmall, lineHeight: 18 },
  successNotice: { minHeight: 42, paddingHorizontal: spacing.md, paddingVertical: spacing.xs, borderWidth: 1, borderColor: colors.successSoft, borderRadius: radius.md, backgroundColor: "#F0FDF4", alignItems: "center", gap: spacing.sm },
  successNoticeText: { flex: 1, color: "#166534", fontSize: type.caption, fontWeight: "700" },
  pageActions: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-end", gap: spacing.sm },
  pageActionsCompact: { width: "100%", alignItems: "center", justifyContent: "space-between", flexDirection: "row", flexWrap: "wrap" },
  pageActionsPhone: { alignItems: "stretch", flexDirection: "column" },
  primaryButton: { minHeight: 44, paddingHorizontal: spacing.lg, borderRadius: radius.pill, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.sm, ...elevation.button },
  primaryButtonFull: { width: "100%" },
  primaryButtonText: { color: colors.white, fontSize: type.label, fontWeight: "900" },

  summaryRow: { width: "100%", flexDirection: "row", gap: spacing.md },
  summaryColumn: { flexDirection: "column" },
  summaryCard: { flex: 1, minWidth: 0, gap: spacing.md },
  summaryTop: { alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  summaryLabel: { color: colors.inkSubtle, fontSize: type.caption, fontWeight: "900", letterSpacing: 0.7, textTransform: "uppercase" },
  summaryCount: { paddingHorizontal: spacing.sm, paddingVertical: 4, borderRadius: radius.pill, backgroundColor: colors.surfaceTint, borderWidth: 1, borderColor: colors.surfaceBlue, color: colors.primary, fontSize: type.micro, fontWeight: "800" },
  summaryCountOperational: { backgroundColor: "#FFFBEB", borderColor: "#FDE68A", color: "#B45309" },
  summaryAmount: { color: colors.success, fontSize: type.numeric, lineHeight: 32, fontWeight: "900", fontVariant: ["tabular-nums"] },
  summaryHint: { color: colors.inkSubtle, fontSize: type.caption, lineHeight: 16 },

  ledgerPanel: { width: "100%", overflow: "hidden" },
  ledgerHeader: { padding: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.line, gap: spacing.md },
  ledgerHeading: { gap: spacing.xs },
  ledgerTitle: { color: colors.ink, fontSize: type.section, lineHeight: 24, fontWeight: "900" },
  ledgerDescription: { color: colors.inkMuted, fontSize: type.caption, lineHeight: 16 },
  ledgerToolbar: { alignItems: "center", justifyContent: "space-between", flexDirection: "row", gap: spacing.md },
  ledgerToolbarCompact: { alignItems: "stretch", flexDirection: "column" },
  ledgerSearchDateGroup: { flex: 1, minWidth: 0, alignItems: "center", flexDirection: "row", gap: spacing.md },
  ledgerSearchDateGroupCompact: { width: "100%", flexWrap: "wrap", justifyContent: "flex-start" },
  ledgerFilterSlot: { alignItems: "center" },
  ledgerFilterSlotCompact: { width: "100%", alignItems: "center", justifyContent: "flex-end", flexDirection: "row" },
  searchInput: { width: 330, minHeight: 40, height: 40, borderWidth: 1, borderColor: colors.line, borderRadius: radius.pill, backgroundColor: colors.canvas },
  searchInputCompact: { width: 330 },
  searchInputPhone: { width: "100%" },
  searchText: { fontSize: type.caption },

  tableDate: { color: colors.inkMuted, fontSize: type.caption, lineHeight: 16 },
  transactionDescription: { color: colors.ink, fontSize: type.label, lineHeight: 17, fontWeight: "800" },
  transactionDetail: { color: colors.inkSubtle, fontSize: type.caption, lineHeight: 15 },
  categoryBadge: { minHeight: 22, paddingHorizontal: spacing.sm, borderRadius: radius.pill, backgroundColor: colors.surfaceTint, borderWidth: 1, borderColor: colors.surfaceBlue, alignItems: "center", alignSelf: "flex-start", justifyContent: "center" },
  categoryBadgeOperational: { backgroundColor: colors.surfaceContainerLow, borderColor: colors.line },
  categoryText: { color: colors.primaryDark, fontSize: type.micro, fontWeight: "700" },
  categoryTextOperational: { color: colors.inkMuted },
  sourceBadge: { minHeight: 22, paddingHorizontal: spacing.sm, borderRadius: radius.pill, backgroundColor: colors.warningSoft, borderWidth: 1, borderColor: "#FDE68A", alignItems: "center", alignSelf: "flex-start", justifyContent: "center" },
  sourceBadgeTransfer: { backgroundColor: colors.surfaceContainerLow, borderColor: colors.line },
  sourceText: { color: "#92400E", fontSize: type.micro, fontWeight: "700" },
  sourceTextTransfer: { color: colors.inkMuted },
  amountText: { color: colors.success, fontSize: type.label, fontWeight: "900", fontVariant: ["tabular-nums"] },
  detailButton: { minHeight: 36, paddingHorizontal: spacing.xs, alignItems: "center", justifyContent: "center" },
  detailButtonText: { color: colors.primary, fontSize: type.caption, fontWeight: "800" },

  emptyState: { minHeight: 180, alignItems: "center", justifyContent: "center", padding: spacing.xl, gap: spacing.xs },
  emptyTitle: { color: colors.ink, fontSize: type.body, fontWeight: "800" },
  emptyCopy: { color: colors.inkMuted, fontSize: type.caption, textAlign: "center" },

  modal: { width: "94%", maxWidth: 560, borderRadius: radius.lg, backgroundColor: colors.white, overflow: "hidden", ...elevation.panel },
  modalHeader: { alignItems: "center", gap: spacing.md, padding: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.line },
  modalIcon: { width: 38, height: 38, borderRadius: radius.sm, backgroundColor: colors.surfaceTint, alignItems: "center", justifyContent: "center" },
  modalHeading: { flex: 1, minWidth: 0, gap: spacing.xs },
  modalTitle: { color: colors.ink, fontSize: type.body, lineHeight: 20, fontWeight: "900" },
  modalSubtitle: { color: colors.inkMuted, fontSize: type.micro, lineHeight: 14 },
  modalBody: { minHeight: 0, padding: 0 },
  modalScroll: { minHeight: 0 },
  modalForm: { padding: spacing.lg, gap: spacing.md },
  formGroup: { gap: spacing.sm },
  formLabel: { color: colors.ink, fontSize: type.caption, lineHeight: 14, fontWeight: "800" },
  formInput: { width: "100%" },
  amountInput: { fontVariant: ["tabular-nums"] },
  inputPrefix: { color: colors.inkMuted, fontSize: type.caption, fontWeight: "800" },
  formError: { color: colors.danger, fontSize: type.micro, lineHeight: 14, fontWeight: "700" },
  selectControl: { minHeight: 48, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, backgroundColor: colors.white, alignItems: "center", justifyContent: "space-between", flexDirection: "row", gap: spacing.sm },
  selectText: { flex: 1, color: colors.ink, fontSize: type.caption, fontWeight: "700" },
  categoryOptions: { maxHeight: 176, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, overflow: "hidden", backgroundColor: colors.white },
  categoryOption: { minHeight: 42, paddingHorizontal: spacing.md, justifyContent: "center", borderBottomWidth: 1, borderBottomColor: colors.line },
  categoryOptionActive: { backgroundColor: colors.surfaceTint },
  categoryOptionText: { color: colors.inkMuted, fontSize: type.caption },
  categoryOptionTextActive: { color: colors.primary, fontWeight: "800" },
  dateTimeRow: { alignItems: "center", gap: spacing.sm },
  dateButton: { flex: 1, minWidth: 0, minHeight: 48, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, backgroundColor: colors.white, alignItems: "center", flexDirection: "row", gap: spacing.sm },
  dateButtonText: { flex: 1, color: colors.ink, fontSize: type.caption, fontWeight: "700" },
  timeInput: { width: 112, minHeight: 48 },
  fundingRow: { flexDirection: "row", gap: spacing.sm },
  fundingButton: { flex: 1, minHeight: 48, paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.xs },
  fundingButtonActive: { borderColor: colors.primary, backgroundColor: colors.surfaceTint },
  fundingText: { color: colors.inkMuted, fontSize: type.caption, fontWeight: "700" },
  fundingTextActive: { color: colors.primary, fontWeight: "900" },
  formHint: { color: colors.inkSubtle, fontSize: type.micro, lineHeight: 15 },
  modalFooter: { width: "100%", padding: spacing.lg, borderTopWidth: 1, borderTopColor: colors.line },
  saveButton: { width: "100%", minHeight: 48, borderRadius: radius.pill, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" },
  saveButtonDisabled: { opacity: 0.45 },
  saveButtonText: { color: colors.white, fontSize: type.caption, fontWeight: "900" },
  cancelButton: { width: "100%", minHeight: 42, marginTop: spacing.xs, alignItems: "center", justifyContent: "center" },
  cancelButtonText: { color: colors.inkMuted, fontSize: type.caption, fontWeight: "700" },

  detailRows: { padding: spacing.lg, gap: spacing.md },
  detailLine: { alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md },
  detailLabel: { color: colors.inkSubtle, fontSize: type.caption },
  detailValue: { maxWidth: "65%", color: colors.ink, fontSize: type.caption, fontWeight: "700", textAlign: "right" },
  detailAmount: { color: colors.success, fontSize: type.body, fontWeight: "900", fontVariant: ["tabular-nums"] },
  detailDivider: { height: 1, backgroundColor: colors.line },
});
