import { StyleSheet } from "react-native";
import { colors, elevation, radius, spacing, typography } from "../../theme";

export const receiptPaperStyles = StyleSheet.create({
  receiptPaper: {
    width: "94%",
    maxWidth: 390,
    backgroundColor: colors.white,
    padding: 17,
    borderTopLeftRadius: radius.md,
    borderTopRightRadius: radius.md,
    gap: 9,
    ...elevation.panel,
  },
  receiptBrand: { alignItems: "center", gap: 2 },
  receiptCup: {
    width: 31,
    height: 31,
    borderRadius: 31,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: "center",
    justifyContent: "center",
  },
  receiptBrandName: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 1,
  },
  receiptSmall: { color: colors.ink, fontSize: 9, lineHeight: 13 },
  receiptTiny: { color: colors.ink, fontSize: 8, lineHeight: 12 },
  receiptMeta: { justifyContent: "space-between" },
  receiptMetaRight: { alignItems: "flex-end" },
  receiptBold: { color: colors.ink, fontSize: 9, fontWeight: "700" },
  queueReceipt: { alignItems: "center", gap: 4, paddingVertical: 5 },
  queueNumber: {
    color: colors.ink,
    fontSize: 36,
    lineHeight: 38,
    fontWeight: "700",
  },
  receiptItems: { gap: 7 },
  receiptTotals: { gap: 5 },
  receiptLine: {
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 6,
  },
  receiptLineName: {
    flex: 1,
    color: colors.ink,
    fontSize: 9,
    fontWeight: "600",
  },
  receiptFooter: { alignItems: "center", gap: 4 },
});

export const receiptModalStyles = StyleSheet.create({
  receiptModal: {
    width: 520,
    maxWidth: "94%",
    padding: 0,
    borderRadius: radius.xl,
    backgroundColor: colors.surface,
    overflow: "hidden",
  },
  receiptModalHeader: {
    width: "100%",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.surfaceTint,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  receiptModalTitle: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    ...typography.sectionTitle,
  },
  receiptModalBody: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surfaceContainerLow,
  },
  receiptModalScroll: { flex: 1, width: "100%", minHeight: 0 },
  receiptModalScrollContent: {
    alignItems: "center",
    paddingVertical: spacing.sm,
  },
  receiptModalFooter: {
    width: "100%",
    alignItems: "stretch",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  receiptPrintButton: {
    width: "100%",
    minHeight: 48,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  receiptPrintButtonText: { color: colors.white, ...typography.button },
  receiptPrintError: {
    color: colors.danger,
    ...typography.helper,
    textAlign: "center",
    paddingTop: spacing.xs,
  },
});
