import { StyleSheet } from "react-native";
import { colors, elevation, radius, spacing } from "../../../theme";

export const styles = StyleSheet.create({
  page: { flex: 1, minHeight: 0, gap: spacing.lg },
  layout: {
    flex: 1,
    minHeight: 0,
    alignItems: "stretch",
    gap: spacing.lg,
  },
  layoutStack: { flexDirection: "column" },
  formColumn: { flex: 1.1, minWidth: 0, minHeight: 0 },
  listColumn: { flex: 0.9, minWidth: 0, minHeight: 0 },
  formCard: { flex: 1, minHeight: 0, overflow: "hidden" },
  listCard: { flex: 1, minHeight: 0, overflow: "hidden" },
  formHeader: { alignItems: "flex-start", gap: 10, marginBottom: spacing.lg },
  formScroll: { flex: 1, minHeight: 0 },
  formScrollContent: { paddingBottom: spacing.sm },
  sectionTitle: { color: colors.ink, fontSize: 16, fontWeight: "900" },
  resetButton: {
    minHeight: 34,
    paddingHorizontal: 9,
    borderRadius: radius.pill,
    backgroundColor: colors.dangerSoft,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  resetText: { color: colors.danger, fontSize: 10, fontWeight: "800" },
  inputText: { flex: 1, color: colors.ink, fontSize: 11 },
  categoryGroup: { gap: spacing.sm },
  categoryLabel: { marginBottom: 0 },
  labelRow: { alignItems: "center", justifyContent: "space-between" },
  categoryRow: { flexWrap: "wrap", gap: 7 },
  formCategory: {
    minHeight: 41,
    paddingHorizontal: 12,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceContainerLow,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  formCategoryActive: { backgroundColor: colors.primary },
  formCategoryText: { color: colors.ink, fontSize: 10, fontWeight: "800" },
  formCategoryTextActive: { color: colors.white },
  stockPanel: {
    backgroundColor: "#F8FAFC",
    borderColor: colors.line,
    shadowOpacity: 0,
  },
  stockRow: { alignItems: "center", gap: 9 },
  stockLabel: { color: colors.ink, fontSize: 11, fontWeight: "800" },
  availabilityPanel: {
    backgroundColor: "#F8FAFC",
    borderColor: colors.line,
    shadowOpacity: 0,
  },
  availabilityRow: { alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  availabilityCopy: { flex: 1, minWidth: 0, gap: 3 },
  availabilityControl: { alignItems: "center", gap: spacing.sm },
  availabilityActiveText: { color: "#166534", fontSize: 10, fontWeight: "900" },
  availabilityInactiveText: { color: colors.inkMuted, fontSize: 10, fontWeight: "900" },
  stockControl: {
    minHeight: 42,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.pill,
    backgroundColor: colors.white,
    alignItems: "center",
    gap: 7,
  },
  stockInput: {
    width: 58,
    minHeight: 36,
    paddingHorizontal: 2,
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  stockInputText: {
    flex: 1,
    color: colors.ink,
    fontSize: 14,
    fontWeight: "900",
    textAlign: "center",
  },
  stockButton: {
    width: 29,
    height: 29,
    borderRadius: 29,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
  },
  stockValue: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "900",
    minWidth: 25,
    textAlign: "center",
  },
  stockUnit: { color: colors.inkMuted, fontSize: 10, paddingRight: 7 },
  photoCard: {
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    alignItems: "center",
    gap: spacing.md,
  },
  photoImage: { width: 92, height: 92, borderRadius: radius.md },
  photoPlaceholder: {
    width: 92,
    height: 92,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  photoPlaceholderText: {
    color: colors.inkMuted,
    fontSize: 8,
    fontWeight: "800",
    textAlign: "center",
  },
  photoTitle: { color: colors.ink, fontSize: 11, fontWeight: "900" },
  savedBadge: {
    color: "#166534",
    backgroundColor: colors.successSoft,
    borderRadius: radius.pill,
    paddingHorizontal: 6,
    paddingVertical: 3,
    fontSize: 9,
    fontWeight: "900",
  },
  uploadButton: {
    minHeight: 38,
    paddingHorizontal: 11,
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
  },
  uploadText: { color: colors.white, fontSize: 10, fontWeight: "900" },
  deletePhoto: {
    minHeight: 38,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 4,
  },
  deletePhotoActive: { backgroundColor: colors.dangerSoft },
  photoActionDisabled: { opacity: 0.5 },
  deletePhotoText: { color: colors.inkMuted, fontSize: 10, fontWeight: "800" },
  deletePhotoTextActive: { color: colors.danger },
  photoError: { color: colors.danger, fontSize: 10, fontWeight: "700" },
  financePanel: { backgroundColor: "#F8FAFC", shadowOpacity: 0 },
  financeHeader: { alignItems: "flex-start", gap: 8 },
  financeStats: {
    gap: 8,
    paddingTop: 13,
    marginTop: 13,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  microLabel: {
    color: colors.inkMuted,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  financeValue: { fontSize: 20, fontWeight: "900" },
  formActions: {
    alignItems: "stretch",
    gap: spacing.sm,
    paddingTop: 2,
  },
  formPublishButton: {
    width: "100%",
    minHeight: 52,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    ...elevation.button,
  },
  listHeader: {
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.md,
  },
  menuCount: {
    color: "#166534",
    backgroundColor: colors.successSoft,
    borderRadius: radius.pill,
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 9,
    fontWeight: "900",
  },
  listSearch: {
    height: 44,
    paddingHorizontal: 12,
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radius.pill,
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
  },
  filterScroll: { height: 55, flexGrow: 0, flexShrink: 0 },
  filterChips: { gap: 6, paddingVertical: spacing.md },
  filterChip: {
    minHeight: 31,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceContainerLow,
    justifyContent: "center",
  },
  filterChipActive: { backgroundColor: colors.primary },
  filterChipText: { color: colors.inkMuted, fontSize: 9, fontWeight: "900" },
  filterChipTextActive: { color: colors.white },
  menuListScroll: { flex: 1, minHeight: 0 },
  menuList: { gap: 7, paddingBottom: spacing.sm },
  listFooter: {
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
    paddingTop: spacing.md,
    marginTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  greenDot: {
    width: 7,
    height: 7,
    borderRadius: 7,
    backgroundColor: colors.success,
  },
  footerStrong: { color: colors.ink, fontSize: 9, fontWeight: "900" },
  footerBullet: { color: colors.inkSubtle, fontSize: 10 },
  footerWarning: { color: colors.warning, fontSize: 9, fontWeight: "900" },
});
