import { StyleSheet } from "react-native";
import { colors, elevation, radius, spacing } from "../../../theme";

export const styles = StyleSheet.create({
  page: { flex: 1, minHeight: 0, gap: spacing.lg },
  pageMobile: { flexGrow: 0, flexShrink: 0, flexBasis: "auto" },
  layout: {
    flex: 1,
    minHeight: 0,
    alignItems: "stretch",
    gap: spacing.lg,
  },
  layoutStack: { flexDirection: "column" },
  layoutMobile: { flexGrow: 0, flexShrink: 0, flexBasis: "auto" },
  formColumn: { flex: 1.1, minWidth: 0, minHeight: 0 },
  formColumnMobile: { flexGrow: 0, flexShrink: 0, flexBasis: "auto" },
  listColumn: { flex: 0.9, minWidth: 0, minHeight: 0 },
  listColumnMobile: { flexGrow: 0, flexShrink: 0, flexBasis: "auto" },
  formCard: { flex: 1, minHeight: 0, overflow: "hidden" },
  formCardMobile: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    overflow: "visible",
  },
  listCard: { flex: 1, minHeight: 0, overflow: "hidden" },
  listCardMobile: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "auto",
    overflow: "visible",
  },
  formHeader: { alignItems: "flex-start", gap: 10, marginBottom: spacing.lg },
  formScroll: { flex: 1, minHeight: 0 },
  formScrollContent: { paddingBottom: spacing.sm },
  mobileFormContent: { flexGrow: 0, flexShrink: 0 },
  sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: "900" },
  sectionTitleTablet: { fontSize: 20 },
  resetButton: {
    minHeight: 34,
    paddingHorizontal: 9,
    borderRadius: radius.pill,
    backgroundColor: colors.dangerSoft,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  resetText: { color: colors.danger, fontSize: 12, fontWeight: "800" },
  resetTextMobile: { fontSize: 12 },
  resetTextTablet: { fontSize: 12 },
  inputText: { flex: 1, color: colors.ink, fontSize: 14 },
  inputTextMobile: { fontSize: 14 },
  inputTextTablet: { fontSize: 15 },
  categoryGroup: { gap: spacing.sm },
  categoryLabel: { marginBottom: 0 },
  labelRow: { alignItems: "center", justifyContent: "space-between" },
  categoryRow: { flexWrap: "wrap", gap: 7 },
  formCategory: {
    minHeight: 41,
    paddingHorizontal: 12,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceContainerLow,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  formCategoryActive: { backgroundColor: colors.primary },
  formCategoryText: { color: colors.ink, fontSize: 13, fontWeight: "800" },
  formCategoryTextMobile: { fontSize: 12 },
  formCategoryTextTablet: { fontSize: 12 },
  formCategoryTextActive: { color: colors.white },
  stockLabel: { color: colors.ink, fontSize: 12, fontWeight: "800" },
  availabilityPanel: {
    backgroundColor: "#F8FAFC",
    borderColor: colors.line,
    shadowOpacity: 0,
  },
  availabilityRow: { alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  photoRow: { alignItems: "center", flexWrap: "wrap", gap: spacing.sm },
  photoImage: { width: 80, height: 80, borderRadius: radius.md, backgroundColor: colors.surfaceContainerLow },
  photoPickEmpty: {
    minHeight: 44,
    alignSelf: "flex-start",
    paddingHorizontal: spacing.md,
    backgroundColor: colors.surfaceTint,
    borderRadius: radius.md,
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
  },
  photoAction: {
    minHeight: 44,
    paddingHorizontal: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  photoActionText: { color: colors.primary, fontSize: 12, fontWeight: "800" },
  photoRemoveAction: {
    minHeight: 44,
    paddingHorizontal: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  photoRemoveText: { color: colors.danger, fontSize: 12, fontWeight: "800" },
  photoActionDisabled: { opacity: 0.5 },
  photoError: { color: colors.danger, fontSize: 12, fontWeight: "700" },
  formActions: {
    alignItems: "stretch",
    gap: spacing.sm,
    paddingTop: 2,
  },
  formPublishButton: {
    width: "100%",
    minHeight: 52,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    ...elevation.button,
  },
  listHeader: {
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.md,
  },
  menuCount: {
    color: "#166534",
    backgroundColor: colors.successSoft,
    borderRadius: radius.pill,
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: "900",
  },
  menuCountAdaptive: { fontSize: 12 },
  menuCountTablet: { fontSize: 12 },
  listSearch: {
    height: 44,
    paddingHorizontal: 12,
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radius.pill,
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
  },
  filterScroll: { height: 55, flexGrow: 0, flexShrink: 0 },
  filterChips: { gap: 6, paddingVertical: spacing.md },
  filterChip: {
    minHeight: 31,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceContainerLow,
    justifyContent: "center",
  },
  filterChipActive: { backgroundColor: colors.primary },
  filterChipText: { color: colors.inkMuted, fontSize: 11, fontWeight: "900" },
  filterChipTextMobile: { fontSize: 12 },
  filterChipTextTablet: { fontSize: 12 },
  filterChipTextActive: { color: colors.white },
  menuListScroll: { flex: 1, minHeight: 0 },
  menuList: { gap: 7, paddingBottom: spacing.sm },
  mobileMenuList: { gap: 7, paddingBottom: spacing.sm },
  listFooter: {
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
    paddingTop: spacing.md,
    marginTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  greenDot: {
    width: 7,
    height: 7,
    borderRadius: 7,
    backgroundColor: colors.success,
  },
  footerStrong: { color: colors.ink, fontSize: 11, fontWeight: "900" },
  footerStrongAdaptive: { fontSize: 12 },
  footerStrongTablet: { fontSize: 12 },
});
