import { StyleSheet } from 'react-native';
import { colors, elevation, radius, spacing } from '../../../theme';

export const styles = StyleSheet.create({
  page: { gap: spacing.lg },
  pageFixed: { flex: 1, minHeight: 0 },
  workspace: { flex: 1, minHeight: 0, alignItems: 'stretch', gap: spacing.lg },
  workspaceStack: { flexDirection: 'column' },
  catalog: { gap: spacing.md, minWidth: 0, minHeight: 0 },
  functionalBar: { padding: 8, borderRadius: radius.lg, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, gap: 8, ...elevation.panel },
  categoryScroll: { gap: spacing.sm, paddingBottom: 2 },
  categoryChip: { minHeight: 40, paddingHorizontal: 14, borderRadius: radius.pill, backgroundColor: colors.surfaceContainerLow, borderWidth: 1, borderColor: 'transparent', flexDirection: 'row', alignItems: 'center', gap: 5 },
  categoryChipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  categoryText: { color: colors.inkMuted, fontSize: 12, fontWeight: '700' },
  categoryTextActive: { color: colors.white },
  categoryCount: { color: colors.inkSubtle, fontSize: 11, fontWeight: '700' },
  categoryCountActive: { color: '#D8E5FF' },
  searchRow: { gap: spacing.md, alignItems: 'center' },
  searchInput: { flex: 1, height: 44, alignItems: 'center', flexDirection: 'row', gap: 8, backgroundColor: colors.surfaceContainerLow, borderWidth: 1, borderColor: 'transparent', borderRadius: radius.pill, paddingHorizontal: 14 },
  inputText: { flex: 1, color: colors.ink, fontSize: 12 },
  clearButton: { minWidth: 34, minHeight: 34, alignItems: 'center', justifyContent: 'center' },
  bestSeller: { minHeight: 44, paddingHorizontal: 14, borderRadius: radius.pill, backgroundColor: colors.surfaceTint, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 },
  bestSellerText: { color: colors.primary, fontSize: 12, fontWeight: '800' },
  productScroll: { flex: 1, minHeight: 0 },
  productScrollContent: { paddingBottom: spacing.xxl },
  productGrid: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  productCard: { flexGrow: 0, flexShrink: 0, minWidth: 0, backgroundColor: colors.white, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, padding: 12, ...elevation.panel },
  productCardFallback: { width: '31.4%', flexBasis: '31.4%' },
  productCardFallbackMobile: { width: '48%', flexBasis: '48%' },
  productImageWrap: { width: '100%', aspectRatio: 4 / 3, borderRadius: radius.md, overflow: 'hidden', backgroundColor: '#F1F3F5', position: 'relative' },
  productImage: { width: '100%', height: '100%' },
  productPlaceholder: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  featureBadge: { position: 'absolute', left: 9, top: 9, paddingHorizontal: 8, paddingVertical: 5, borderRadius: radius.pill, backgroundColor: colors.primary },
  featureText: { color: colors.white, fontSize: 11, fontWeight: '900' },
  stockBadge: { position: 'absolute', right: 9, bottom: 9, paddingHorizontal: 8, paddingVertical: 5, borderRadius: radius.pill, backgroundColor: 'rgba(255,255,255,0.94)', flexDirection: 'row', alignItems: 'center', gap: 5 },
  stockDot: { width: 6, height: 6, borderRadius: 6, backgroundColor: colors.success },
  stockText: { color: colors.success, fontSize: 11, fontWeight: '800' },
  stockDotEmpty: { backgroundColor: colors.danger },
  stockTextEmpty: { color: colors.danger },
  productInfo: { paddingTop: 11, gap: 4 },
  productName: { color: colors.ink, fontSize: 13, lineHeight: 18, fontWeight: '800' },
  productDescription: { color: colors.inkMuted, fontSize: 11, lineHeight: 15 },
  productBottom: { alignItems: 'center', justifyContent: 'space-between', marginTop: 7 },
  productPrice: { color: colors.success, fontSize: 14, fontWeight: '900' },
  plusButton: { width: 36, height: 36, borderRadius: 36, backgroundColor: colors.surfaceTint, borderWidth: 1, borderColor: '#BFDBFE', alignItems: 'center', justifyContent: 'center' },
  cartPanel: { width: 420, overflow: 'hidden' },
  cartPanelFixed: { height: '100%', minHeight: 0 },
  cartPanelCompact: { width: '100%', minHeight: 460 },
  cartHeader: { minHeight: 62, alignItems: 'center', paddingHorizontal: 16, backgroundColor: colors.surfaceContainerLow, borderBottomWidth: 1, borderBottomColor: colors.line },
  cartHeaderTitle: { flex: 1, alignItems: 'center', gap: 8 },
  cartTitle: { color: colors.ink, fontSize: 15, fontWeight: '900' },
  cartOrder: { color: colors.primary, fontSize: 11, fontWeight: '900', backgroundColor: colors.surfaceTint, paddingHorizontal: 8, paddingVertical: 4, borderRadius: radius.pill },
  moreButton: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center' },
  clearCartDisabled: { opacity: 0.45 },
  cartItems: { flex: 1, minHeight: 0 },
  cartItemsContent: { padding: 12, gap: 8 },
  cartItem: { flexDirection: 'row', alignItems: 'center', padding: 8, borderRadius: radius.lg, backgroundColor: colors.surfaceContainerLow, borderWidth: 1, borderColor: colors.line, gap: 8 },
  cartThumb: { width: 40, height: 40, flexShrink: 0, borderRadius: 20, overflow: 'hidden', backgroundColor: colors.surfaceTint, alignItems: 'center', justifyContent: 'center' },
  cartThumbImage: { width: '100%', height: '100%' },
  cartItemInfo: { flex: 1, minWidth: 0, gap: 2 },
  cartItemHeading: { alignItems: 'flex-start', justifyContent: 'space-between', gap: 6 },
  cartItemName: { flex: 1, minWidth: 0, color: colors.ink, fontSize: 11, lineHeight: 15, fontWeight: '800' },
  cartItemPrice: { flexShrink: 0, color: colors.success, fontSize: 12, fontWeight: '900', marginTop: 1 },
  cartCategory: { flex: 1, minWidth: 0, color: colors.inkMuted, fontSize: 10, lineHeight: 14 },
  cartItemMetaRow: { alignItems: 'center', justifyContent: 'space-between', gap: 4 },
  cartItemControls: { alignItems: 'center', gap: spacing.sm },
  quantityControl: { alignItems: 'center', borderWidth: 1, borderColor: colors.line, borderRadius: radius.pill, paddingHorizontal: 3 },
  quantityButton: { width: 24, height: 28, alignItems: 'center', justifyContent: 'center' },
  quantityValue: { color: colors.ink, fontSize: 11, fontWeight: '900', minWidth: 12, textAlign: 'center' },
  removeButton: { width: 25, height: 34, alignItems: 'center', justifyContent: 'center' },
  cartSummary: { gap: 12, padding: 16, backgroundColor: colors.surfaceContainerLow, borderTopWidth: 1, borderTopColor: colors.line },
  summaryRow: { justifyContent: 'space-between', alignItems: 'center' },
  cupChip: { alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 6, borderRadius: radius.pill, backgroundColor: colors.surfaceTint },
  summaryLabel: { color: colors.primary, fontSize: 10, fontWeight: '800' },
  summaryValue: { color: colors.success, fontSize: 21, fontWeight: '900' },
  subtotalLabel: { color: colors.inkMuted, fontSize: 10, fontWeight: '700' },
  checkoutButton: { minHeight: 54, paddingHorizontal: 17, backgroundColor: colors.primary, borderRadius: radius.pill, alignItems: 'center', justifyContent: 'space-between', flexDirection: 'row', ...elevation.button },
  checkoutText: { color: colors.white, fontSize: 13, fontWeight: '900' },
});
