import { StyleSheet } from "react-native";
import {
  colors,
  elevation,
  fieldHeight,
  radius,
  spacing,
  typography,
} from "../../theme";

export const styles = StyleSheet.create({
  trigger: {
    minWidth: 190,
    minHeight: fieldHeight,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.lineStrong,
    borderRadius: radius.md,
    backgroundColor: colors.canvas,
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    gap: spacing.sm,
  },
  triggerFullWidth: { width: "100%", minWidth: 0 },
  triggerDisabled: {
    borderColor: colors.line,
    backgroundColor: colors.surfaceContainerLow,
  },
  triggerText: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    ...typography.input,
    fontWeight: "500",
  },
  triggerTextDisabled: { color: colors.inkSubtle },
  popup: {
    padding: spacing.xs,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    overflow: "hidden",
    ...elevation.panel,
  },
  backdrop: { backgroundColor: "transparent" },
  popupBody: { width: "100%", flexShrink: 1, alignSelf: "stretch" },
  searchInput: {
    width: "100%",
    height: 40,
    minHeight: 40,
    paddingHorizontal: spacing.sm,
    marginBottom: spacing.xs,
    backgroundColor: colors.surfaceContainerLow,
    borderColor: colors.line,
  },
  optionList: { width: "100%", flexShrink: 1 },
  optionListContent: { gap: 2, paddingBottom: 2 },
  option: {
    width: "100%",
    minHeight: fieldHeight,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    gap: spacing.sm,
  },
  optionSelected: { backgroundColor: colors.surfaceTint },
  optionLabel: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    ...typography.input,
    fontWeight: "500",
  },
  optionLabelSelected: { color: colors.primary, fontWeight: "600" },
  optionDetail: { color: colors.inkMuted, ...typography.helper, fontWeight: "600" },
  emptyResult: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
    color: colors.inkMuted,
    ...typography.helper,
    textAlign: "center",
  },
});
