import { StyleSheet } from 'react-native';
import { colors, elevation, radius } from '../../../theme';

export const styles = StyleSheet.create({
  page: { gap: 16 }, pageFill: { flex: 1, minHeight: 0 },
  livePill: { alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: radius.pill, backgroundColor: colors.successSoft }, liveText: { color: colors.success, fontSize: 11, fontWeight: '900' },
  summaryBar: { backgroundColor: colors.white }, summaryItems: { gap: 10 }, summaryWrap: { flexWrap: 'wrap' }, summaryItem: { flex: 1, minWidth: 190, minHeight: 72, paddingHorizontal: 14, borderRadius: radius.md, alignItems: 'center', gap: 11 }, summaryIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, summaryLabel: { color: colors.inkMuted, fontSize: 9, fontWeight: '900', letterSpacing: 0.6 }, summaryValue: { fontSize: 24, lineHeight: 27, fontWeight: '900' }, summaryHelper: { color: colors.inkMuted, fontSize: 10, fontWeight: '700' },
  kdsTitle: { justifyContent: 'space-between', alignItems: 'center', paddingTop: 3 }, kdsHeading: { color: colors.ink, fontSize: 18, fontWeight: '900' },
  columns: { alignItems: 'stretch', gap: 12 }, columnsFill: { flex: 1, minHeight: 0 }, columnsStack: { flexDirection: 'column' }, column: { flex: 1, width: '100%', minWidth: 0, minHeight: 430, backgroundColor: colors.surfaceContainerLow }, columnFill: { flex: 1, minHeight: 0 }, columnHeader: { alignItems: 'center', gap: 9, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: colors.line }, columnIcon: { width: 38, height: 38, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, columnTitle: { color: colors.ink, fontSize: 13, fontWeight: '900' }, columnSubtitle: { color: colors.inkMuted, fontSize: 10 }, columnCount: { minWidth: 25, height: 25, borderRadius: 25, alignItems: 'center', justifyContent: 'center' }, columnCountText: { fontSize: 11, fontWeight: '900' },
  ticketListScroll: { flex: 1, minHeight: 0 }, ticketList: { gap: 10, paddingTop: 12 }, ticket: { backgroundColor: colors.white, borderRadius: radius.md, gap: 10, ...elevation.panel }, preparingTicket: { borderWidth: 2, borderColor: '#93B4FF' }, readyTicket: { borderColor: '#86EFAC' }, completedTicket: { opacity: 0.64, backgroundColor: '#F8FAFC' }, completedText: { color: colors.inkMuted }, ticketTop: { alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 }, ticketNumber: { color: colors.ink, fontSize: 17, fontWeight: '900' }, ticketTime: { color: colors.inkMuted, fontSize: 10 }, progressCount: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 4, borderRadius: radius.pill, backgroundColor: colors.surfaceTint }, progressCountText: { color: colors.primary, fontSize: 9, fontWeight: '900' },
  ticketItems: { gap: 8 }, ticketItem: { alignItems: 'center', gap: 8 }, itemCheckTarget: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center' }, itemCheck: { width: 23, height: 23, borderRadius: 23, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, itemCheckOpen: { borderColor: colors.primary, backgroundColor: colors.surfaceTint }, itemCheckDone: { borderColor: colors.primary, backgroundColor: colors.primary }, itemCheckReady: { borderColor: colors.success, backgroundColor: colors.success }, itemCopy: { flex: 1, minWidth: 0, gap: 2 }, itemName: { color: colors.ink, fontSize: 11, fontWeight: '800' }, itemDetail: { color: colors.inkMuted, fontSize: 9, lineHeight: 13 }, preparedBadge: { alignSelf: 'center', paddingHorizontal: 7, paddingVertical: 4, borderRadius: radius.pill, backgroundColor: colors.successSoft }, preparedBadgeText: { color: colors.success, fontSize: 8, fontWeight: '900' },
  progressTrack: { height: 6, borderRadius: radius.pill, backgroundColor: colors.surfaceBlue, overflow: 'hidden' }, progressFill: { width: '50%', height: '100%', borderRadius: radius.pill, backgroundColor: colors.primary }, ticketButton: { minHeight: 39, borderRadius: radius.sm, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 }, disabledButton: { backgroundColor: '#CBD5E1' }, ticketButtonText: { color: colors.white, fontSize: 10, fontWeight: '900' }, emptyText: { color: colors.inkSubtle, fontSize: 11, textAlign: 'center', paddingTop: 10 },
});
