import { StyleSheet } from 'react-native';
import { colors, elevation, radius, type, typography } from '../../../theme';

export const styles = StyleSheet.create({
  page: { gap: 16 },
  pageFill: { flex: 1, minHeight: 0 },
  livePill: {
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.sm,
    backgroundColor: colors.successSoft,
  },
  liveText: { color: colors.success, fontSize: type.micro, lineHeight: 17, fontWeight: '600' },
  summaryBar: { backgroundColor: colors.white },
  summaryItems: { gap: 10 },
  summaryWrap: { flexWrap: 'wrap' },
  summaryItem: {
    flex: 1,
    minWidth: 190,
    minHeight: 72,
    paddingHorizontal: 14,
    borderRadius: radius.lg,
    alignItems: 'center',
    gap: 11,
  },
  summaryIcon: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryLabel: {
    color: colors.inkMuted,
    fontSize: type.overline,
    lineHeight: 15,
    fontWeight: '600',
    letterSpacing: 0.6,
  },
  summaryLabelAdaptive: { fontSize: type.overline, lineHeight: 15 },
  summaryValue: { color: colors.ink, fontSize: type.numeric, lineHeight: 29, fontWeight: '700' },
  summaryValueMobile: { fontSize: type.amount, lineHeight: 25 },
  summaryValueTablet: { fontSize: type.amount, lineHeight: 25 },
  summaryHelper: { color: colors.inkMuted, fontSize: type.micro, lineHeight: 17, fontWeight: '500' },
  summaryHelperAdaptive: { fontSize: type.micro, lineHeight: 17 },
  kdsTitle: { justifyContent: 'space-between', alignItems: 'center', paddingTop: 3 },
  kdsTitleNarrow: { flexDirection: 'column', alignItems: 'flex-start', gap: 8 },
  kdsHeading: { color: colors.ink, ...typography.pageTitle },
  kdsHeadingMobile: { fontSize: type.title, lineHeight: 29 },
  kdsHeadingTablet: { fontSize: type.title, lineHeight: 29 },
  columns: { alignItems: 'stretch', gap: 12 },
  columnsFill: { flex: 1, minHeight: 0 },
  columnsStack: { flexDirection: 'column' },
  column: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    width: '100%',
    minWidth: 0,
    minHeight: 430,
    backgroundColor: colors.surfaceContainerLow,
  },
  columnFill: { flexGrow: 1, flexShrink: 1, flexBasis: 0, minHeight: 0 },
  columnCompact: { flexGrow: 0, flexShrink: 0, flexBasis: 'auto', minHeight: 0 },
  columnHeader: {
    alignItems: 'center',
    gap: 9,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  columnIcon: {
    width: 38,
    height: 38,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  columnTitle: { color: colors.ink, fontSize: type.bodySmall, lineHeight: 21, fontWeight: '600' },
  columnTitleMobile: { fontSize: type.bodySmall, lineHeight: 21 },
  columnTitleTablet: { fontSize: type.bodySmall, lineHeight: 21 },
  columnSubtitle: { color: colors.inkMuted, fontSize: type.micro, lineHeight: 17 },
  columnSubtitleAdaptive: { fontSize: type.micro, lineHeight: 17 },
  columnCount: { minWidth: 25, height: 25, borderRadius: radius.sm, alignItems: 'center', justifyContent: 'center' },
  columnCountText: { fontSize: type.micro, lineHeight: 17, fontWeight: '600' },
  ticketListScroll: { flex: 1, minHeight: 0 },
  ticketList: { gap: 10, paddingTop: 12 },
  ticket: { backgroundColor: colors.white, borderRadius: radius.lg, gap: 10, ...elevation.panel },
  waitingTicket: { borderWidth: 1, borderColor: colors.warning },
  preparingTicket: { borderWidth: 2, borderColor: colors.primary },
  readyTicket: { borderWidth: 1, borderColor: colors.success },
  completedTicket: { opacity: 0.64, backgroundColor: colors.surfaceContainerLow },
  completedText: { color: colors.inkMuted },
  ticketTop: { alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  ticketNumber: { color: colors.ink, fontSize: type.bodySmall, lineHeight: 21, fontWeight: '600' },
  ticketNumberMobile: { fontSize: type.bodySmall, lineHeight: 21 },
  ticketNumberTablet: { fontSize: type.bodySmall, lineHeight: 21 },
  ticketTime: { color: colors.inkMuted, fontSize: type.micro, lineHeight: 17 },
  ticketTimeAdaptive: { fontSize: type.micro, lineHeight: 17 },
  ticketTimeTablet: { fontSize: type.micro, lineHeight: 17 },
  progressCount: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radius.sm,
    backgroundColor: colors.surfaceTint,
  },
  progressCountText: { color: colors.primaryDark, fontSize: type.micro, lineHeight: 17, fontWeight: '600' },
  progressCountTextAdaptive: { fontSize: type.micro, lineHeight: 17 },
  ticketItems: { gap: 8 },
  ticketItem: { alignItems: 'center', gap: 8 },
  itemCheckTarget: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  itemCheck: {
    width: 23,
    height: 23,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemCheckOpen: { borderColor: colors.primary, backgroundColor: colors.surfaceTint },
  itemCheckDone: { borderColor: colors.primary, backgroundColor: colors.primary },
  itemCheckReady: { borderColor: colors.success, backgroundColor: colors.success },
  itemCopy: { flex: 1, minWidth: 0, gap: 2 },
  itemName: { color: colors.ink, fontSize: type.bodySmall, lineHeight: 21, fontWeight: '600' },
  itemNameAdaptive: { fontSize: type.bodySmall, lineHeight: 21 },
  itemDetail: { color: colors.inkMuted, fontSize: type.micro, lineHeight: 17 },
  itemDetailAdaptive: { fontSize: type.micro, lineHeight: 17 },
  preparedBadge: {
    alignSelf: 'center',
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: radius.sm,
    backgroundColor: colors.successSoft,
  },
  preparedBadgeText: { color: colors.success, fontSize: type.micro, lineHeight: 17, fontWeight: '600' },
  preparedBadgeTextAdaptive: { fontSize: type.micro, lineHeight: 17 },
  progressTrack: { height: 6, borderRadius: radius.pill, backgroundColor: colors.surfaceBlue, overflow: 'hidden' },
  progressFill: { width: '50%', height: '100%', borderRadius: radius.pill, backgroundColor: colors.primary },
  ticketButton: {
    minHeight: 44,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  disabledButton: { backgroundColor: '#CBD5E1' },
  ticketButtonText: { color: colors.white, ...typography.button },
  ticketButtonTextAdaptive: { fontSize: type.button, lineHeight: 18 },
  disabledButtonText: { color: colors.ink },
});
