import { StyleSheet } from "react-native";
import { colors, elevation, radius, spacing } from "../../../../theme";

export const hppModalStyles = StyleSheet.create({
  hppModal: {
    width: 620,
    maxWidth: "94%",
    borderRadius: radius.xl,
    backgroundColor: colors.surface,
    padding: 0,
    overflow: "hidden",
  },
  hppModalHeader: {
    width: "100%",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.surfaceTint,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  hppHeaderIcon: {
    width: 42,
    height: 42,
    flexShrink: 0,
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  hppHeaderCopy: { flex: 1, minWidth: 0, gap: 2 },
  hppTitle: { color: colors.ink, fontSize: 16, fontWeight: "900" },
  hppModalBody: { paddingHorizontal: spacing.lg, paddingTop: spacing.md },
  hppBodyContent: { gap: spacing.md, paddingBottom: spacing.sm },
  hppPricePanel: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: colors.surfaceTint,
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  hppPanelHeading: { alignItems: "center", gap: spacing.sm },
  hppPanelTitle: { color: colors.ink, fontSize: 12, fontWeight: "900" },
  hppFieldLabel: { color: colors.inkMuted, fontSize: 10, fontWeight: "800" },
  hppPriceInput: {
    minHeight: 48,
    borderRadius: radius.md,
    borderColor: colors.line,
    backgroundColor: colors.white,
  },
  hppPriceInputText: { color: colors.success, fontSize: 18, fontWeight: "900" },
  hppCurrency: { color: colors.success, fontSize: 12, fontWeight: "900" },
  hppComponentsHeading: {
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: spacing.sm,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  hppComponentsTitleGroup: { flex: 1, minWidth: 180, gap: 3 },
  addIngredientButton: {
    minHeight: 38,
    paddingHorizontal: spacing.md,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  addIngredientText: { color: colors.white, fontSize: 10, fontWeight: "900" },
  hppComponentsList: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    overflow: "hidden",
  },
  hppEmptyState: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    color: colors.inkMuted,
    fontSize: 10,
    lineHeight: 15,
    textAlign: "center",
  },
  hppComponentRow: {
    minHeight: 68,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    alignItems: "center",
    gap: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  hppComponentRowLast: { borderBottomWidth: 0 },
  hppComponentIcon: {
    width: 36,
    height: 36,
    flexShrink: 0,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceTint,
    alignItems: "center",
    justifyContent: "center",
  },
  hppComponentCopy: { flex: 1, minWidth: 0, gap: 2 },
  hppComponentName: { color: colors.ink, fontSize: 11, fontWeight: "900" },
  hppComponentDetail: { color: colors.inkMuted, fontSize: 10, lineHeight: 14 },
  hppComponentCostInput: {
    width: 138,
    minHeight: 42,
    flexShrink: 0,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.md,
    borderColor: colors.line,
    backgroundColor: colors.surfaceContainerLow,
  },
  hppComponentCostText: {
    flex: 1,
    color: colors.success,
    fontSize: 11,
    fontWeight: "900",
    textAlign: "right",
  },
  hppSummary: {
    flexWrap: "wrap",
    alignItems: "center",
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: colors.successSoft,
    borderWidth: 1,
    borderColor: "#BBF7D0",
  },
  hppSummaryIcon: {
    width: 36,
    height: 36,
    flexShrink: 0,
    borderRadius: radius.pill,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  hppSummaryCopy: { flex: 1, minWidth: 150, gap: 2 },
  hppSummaryLabel: { color: colors.inkMuted, fontSize: 10, fontWeight: "800" },
  hppProfit: { color: colors.success, fontSize: 11, fontWeight: "900" },
  hppProfitNegative: { color: colors.danger },
  hppTotalBadge: {
    minWidth: 115,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radius.pill,
    backgroundColor: colors.white,
    alignItems: "center",
    gap: 2,
  },
  hppTotalLabel: { color: colors.success, fontSize: 10, fontWeight: "800" },
  hppTotalValue: { color: colors.success, fontSize: 12, fontWeight: "900" },
  hppModalFooter: {
    width: "100%",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.surfaceContainerLow,
  },
  hppSaveButton: {
    width: "100%",
    minHeight: 48,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    ...elevation.button,
  },
});
