import { StyleSheet } from "react-native";
import { colors, radius, spacing } from "../../../../theme";

export const ingredientModalStyles = StyleSheet.create({
  ingredientModal: {
    width: 480,
    maxWidth: "94%",
    borderRadius: radius.xl,
    backgroundColor: colors.surface,
    padding: 0,
    overflow: "hidden",
  },
  ingredientModalHeader: {
    width: "100%",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.surfaceTint,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  ingredientForm: { width: "100%", gap: spacing.md },
  ingredientField: { gap: 2 },
  ingredientFieldsRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  unitField: { flex: 1, minWidth: 0, gap: 2 },
  ingredientCostField: { flex: 1, minWidth: 0, gap: 2 },
  ingredientFieldLabel: { height: 20, marginBottom: 0 },
  unitSelect: {
    minHeight: 48,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceContainerLow,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.xs,
  },
  unitSelectText: { flex: 1, color: colors.ink, fontSize: 10, fontWeight: "800" },
  ingredientCostInput: {
    minHeight: 48,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.pill,
    borderColor: colors.line,
    backgroundColor: colors.surfaceContainerLow,
  },
  unitOptions: { flexWrap: "wrap", gap: spacing.xs },
  unitOption: {
    minHeight: 36,
    paddingHorizontal: spacing.sm,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.pill,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  unitOptionSelected: { borderColor: colors.primary, backgroundColor: colors.surfaceTint },
  unitOptionText: { color: colors.inkMuted, fontSize: 9, fontWeight: "800" },
  unitOptionTextSelected: { color: colors.primary },
  ingredientActions: {
    width: "100%",
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  ingredientSubmitButton: {
    width: "100%",
    minHeight: 48,
    paddingHorizontal: spacing.md,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 5,
  },
});
