import { StyleSheet } from "react-native";
import {
  colors,
  radius,
  spacing,
  type,
  typography,
} from "../../../theme";

export const styles = StyleSheet.create({
  page: { width: "100%", gap: spacing.md, paddingBottom: spacing.xxl },
  searchInputFilter: { width: "100%" },
  primaryAction: { minHeight: 44, flexShrink: 0, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: colors.primary, borderWidth: 1, borderColor: colors.primary, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.xs },
  primaryActionFullWidth: { width: "100%" },
  primaryActionText: { color: colors.white, ...typography.button },
  inventoryItemColumn: { gap: spacing.xs },
  inventoryItemNameRow: { alignItems: "center", gap: spacing.xs },
  lowStockMark: { width: 6, height: 6, borderRadius: 6, backgroundColor: colors.warning },
  itemName: { color: colors.ink, fontSize: type.label, lineHeight: 18, fontWeight: "600" },
  itemDescription: { color: colors.inkSubtle, fontSize: type.micro, lineHeight: 17 },
  cellMuted: { color: colors.inkMuted, fontSize: type.caption, lineHeight: 18 },
  cellValue: { color: colors.ink, fontSize: type.label, fontWeight: "700", fontVariant: ["tabular-nums"] },
  cellPrice: { color: colors.ink, fontSize: type.label, fontWeight: "700", fontVariant: ["tabular-nums"] },
  cellWarning: { color: colors.warning },
  statusBadge: { minHeight: 22, paddingHorizontal: spacing.sm, borderRadius: radius.sm, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.xs },
  statusBadgeSafe: { backgroundColor: colors.successSoft, borderWidth: 1, borderColor: colors.successSoft },
  statusBadgeLow: { backgroundColor: colors.warningSoft, borderWidth: 1, borderColor: colors.warningSoft },
  statusBadgeText: { fontSize: type.micro, fontWeight: "600" },
  dateTag: { paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, borderRadius: radius.sm, backgroundColor: colors.surfaceTint, borderWidth: 1, borderColor: colors.surfaceBlue, color: colors.primary, fontSize: type.micro, lineHeight: 17, fontWeight: "600" },
  historyItemCell: { gap: spacing.xs },
  typeBadge: { minHeight: 22, paddingHorizontal: spacing.sm, borderRadius: radius.sm, borderWidth: 1, alignItems: "center", alignSelf: "flex-start", flexDirection: "row", gap: spacing.xs },
  typeBadgePurchase: { backgroundColor: colors.successSoft, borderColor: colors.successSoft },
  typeBadgeCorrection: { backgroundColor: colors.warningSoft, borderColor: colors.warningSoft },
  typeBadgeText: { fontSize: type.micro, lineHeight: 17, fontWeight: "600" },
  modal: { width: "94%", maxWidth: 620, borderRadius: radius.lg, backgroundColor: colors.white, overflow: "hidden" },
  modalHeader: { alignItems: "center", gap: spacing.md, padding: spacing.lg, paddingBottom: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.line },
  modalIcon: { width: 38, height: 38, borderRadius: radius.md, backgroundColor: colors.surfaceTint, alignItems: "center", justifyContent: "center" },
  modalHeading: { flex: 1, minWidth: 0, gap: spacing.xs },
  modalTitle: { color: colors.ink, ...typography.sectionTitle },
  modalSubtitle: { color: colors.inkMuted, ...typography.description },
  modalBody: { padding: 0 },
  modalScroll: { maxHeight: 560 },
  modalForm: { padding: spacing.lg, gap: spacing.md },
  formGroup: { gap: spacing.sm },
  formLabel: { color: colors.ink, ...typography.label },
  formInput: { width: "100%" },
  formInputText: { ...typography.input },
  formHint: { color: colors.inkMuted, ...typography.helper },
  formError: { color: colors.danger, ...typography.helper, fontWeight: "600" },
  inputPrefix: { color: colors.inkMuted, fontSize: type.caption, fontWeight: "600" },
  summaryBox: { padding: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, backgroundColor: colors.surfaceContainerLow, gap: spacing.sm },
  summaryLine: { alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  summaryLineLabel: { color: colors.inkMuted, fontSize: type.caption },
  summaryLineValue: { color: colors.ink, fontSize: type.caption, fontWeight: "600" },
  textWarning: { color: colors.warning },
  textSuccess: { color: colors.success },
  modalFooter: { width: "100%", padding: spacing.lg, borderTopWidth: 1, borderTopColor: colors.line, alignItems: "stretch", justifyContent: "center", flexDirection: "column" },
  saveButton: { width: "100%", minHeight: 48, paddingHorizontal: spacing.lg, borderRadius: radius.md, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" },
  saveButtonDisabled: { opacity: 0.45 },
  saveButtonText: { color: colors.white, ...typography.button },
});
