import { StyleSheet } from "react-native";
import { colors, elevation, radius, spacing, type } from "../../../theme";

export const styles = StyleSheet.create({
  page: { width: "100%", gap: spacing.md, paddingBottom: spacing.xxl },
  sectionPanel: { width: "100%", overflow: "hidden" },
  inventoryToolbar: { position: "relative", zIndex: 20, minHeight: 66, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, gap: spacing.md, alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: colors.line, backgroundColor: colors.white },
  inventoryToolbarMobile: { alignItems: "stretch", flexDirection: "column" },
  toolbarControls: { flex: 1, minWidth: 0, flexDirection: "row", flexWrap: "nowrap", alignItems: "center", gap: spacing.sm },
  toolbarControlsMobile: { width: "100%", flex: 0, alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  toolbarControlsDropdownOpen: { position: "relative", zIndex: 30 },
  searchInput: { width: 245, minHeight: 40, height: 40, borderWidth: 1, borderColor: colors.line, borderRadius: radius.pill, backgroundColor: colors.white },
  searchInputMobile: { width: "100%" },
  categoryControlWrap: { position: "relative", zIndex: 2, flexShrink: 0 },
  categoryControlWrapMobile: { width: 132 },
  selectControl: { width: 132, minHeight: 40, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radius.pill, backgroundColor: colors.white, alignItems: "center", justifyContent: "space-between", flexDirection: "row", gap: spacing.xs },
  selectControlText: { flex: 1, color: colors.inkMuted, fontSize: type.caption, fontWeight: "700" },
  categoryMenu: { position: "absolute", top: 44, left: 0, width: 190, paddingVertical: spacing.xs, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, zIndex: 10, ...elevation.panel },
  categoryMenuItem: { minHeight: 40, paddingHorizontal: spacing.md, justifyContent: "center" },
  categoryMenuItemActive: { backgroundColor: colors.surfaceTint },
  categoryMenuText: { color: colors.inkMuted, fontSize: type.caption },
  categoryMenuTextActive: { color: colors.primary, fontWeight: "800" },
  resultCount: { color: colors.inkSubtle, fontSize: type.caption, fontWeight: "700", flexShrink: 0 },
  resultCountMobile: { flex: 1, minWidth: 0 },
  primaryAction: { minHeight: 40, flexShrink: 0, paddingHorizontal: spacing.md, borderRadius: radius.pill, backgroundColor: colors.primary, borderWidth: 1, borderColor: colors.primary, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.xs },
  primaryActionFullWidth: { width: "100%" },
  primaryActionText: { color: colors.white, fontSize: type.label, fontWeight: "800" },
  inventoryRowSelected: { backgroundColor: colors.surfaceTint },
  inventoryItemColumn: { gap: spacing.xs },
  inventoryItemNameRow: { alignItems: "center", gap: spacing.xs },
  lowStockMark: { width: 6, height: 6, borderRadius: 6, backgroundColor: colors.warning },
  itemName: { color: colors.ink, fontSize: type.label, lineHeight: 16, fontWeight: "700" },
  itemDescription: { color: colors.inkSubtle, fontSize: type.micro, lineHeight: 14 },
  cellMuted: { color: colors.inkMuted, fontSize: type.caption, lineHeight: 16 },
  cellValue: { color: colors.ink, fontSize: type.label, fontWeight: "700", fontVariant: ["tabular-nums"] },
  cellPrice: { color: colors.success, fontSize: type.label, fontWeight: "700", fontVariant: ["tabular-nums"] },
  cellWarning: { color: colors.warning },
  cellDanger: { color: colors.danger },
  statusBadge: { minHeight: 22, paddingHorizontal: spacing.sm, borderRadius: radius.pill, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.xs },
  statusBadgeSafe: { backgroundColor: colors.successSoft, borderWidth: 1, borderColor: colors.successSoft },
  statusBadgeLow: { backgroundColor: colors.warningSoft, borderWidth: 1, borderColor: colors.warningSoft },
  statusBadgeText: { fontSize: type.micro, fontWeight: "700" },
  actionButton: { minHeight: 36, paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.primary, borderRadius: radius.sm, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.xs },
  actionButtonText: { color: colors.primary, fontSize: type.micro, fontWeight: "700" },
  emptyTableText: { padding: spacing.xl, color: colors.inkMuted, fontSize: type.bodySmall },
  historyToolbar: { minHeight: 70, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, gap: spacing.md, alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: colors.line, backgroundColor: colors.white },
  historyToolbarMobile: { alignItems: "stretch", flexDirection: "column" },
  toolbarHeading: { flexGrow: 1, flexShrink: 1, minWidth: 240, maxWidth: 420, gap: spacing.xs },
  toolbarHeadingMobile: { width: "100%", minWidth: 0, maxWidth: "100%", flexGrow: 0, flexShrink: 0 },
  historyTitleRow: { alignItems: "center", gap: spacing.sm, flexWrap: "wrap" },
  historyTitle: { color: colors.ink, fontSize: type.body, lineHeight: 20, fontWeight: "800" },
  sectionDescription: { color: colors.inkMuted, fontSize: type.caption, lineHeight: 15 },
  dateTag: { paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, borderRadius: radius.pill, backgroundColor: colors.surfaceTint, borderWidth: 1, borderColor: colors.surfaceBlue, color: colors.primary, fontSize: type.micro, fontWeight: "700" },
  historyControls: { flexGrow: 1, flexShrink: 1, minWidth: 0, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  historyControlsMobile: { width: "100%", minHeight: 40, flexGrow: 0, flexShrink: 1, alignItems: "center", justifyContent: "space-between", flexWrap: "wrap" },
  historySearchDateGroup: { flexShrink: 1, alignItems: "center", flexDirection: "row", gap: spacing.sm },
  historySearchDateGroupPhone: { width: "100%", flexWrap: "wrap" },
  historySearchInput: { width: 190, minHeight: 40, height: 40, borderWidth: 1, borderColor: colors.line, borderRadius: radius.pill, backgroundColor: colors.white },
  historySearchInputCompact: { width: 245 },
  historySearchInputMobile: { width: "100%" },
  historyItemCell: { gap: spacing.xs },
  typeBadge: { minHeight: 22, paddingHorizontal: spacing.sm, borderRadius: radius.pill, borderWidth: 1, alignItems: "center", alignSelf: "flex-start", flexDirection: "row", gap: spacing.xs },
  typeBadgePurchase: { backgroundColor: colors.successSoft, borderColor: colors.successSoft },
  typeBadgeSale: { backgroundColor: colors.dangerSoft, borderColor: colors.dangerSoft },
  typeBadgeCorrection: { backgroundColor: colors.warningSoft, borderColor: colors.warningSoft },
  typeBadgeText: { fontSize: type.micro, fontWeight: "700" },
  modal: { width: "94%", maxWidth: 620, borderRadius: radius.lg, backgroundColor: colors.white, overflow: "hidden" },
  modalHeader: { alignItems: "center", gap: spacing.md, padding: spacing.lg, paddingBottom: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.line },
  modalIcon: { width: 38, height: 38, borderRadius: radius.sm, backgroundColor: colors.surfaceTint, alignItems: "center", justifyContent: "center" },
  modalHeading: { flex: 1, minWidth: 0, gap: spacing.xs },
  modalTitle: { color: colors.ink, fontSize: type.body, lineHeight: 20, fontWeight: "800" },
  modalSubtitle: { color: colors.inkMuted, fontSize: type.micro, lineHeight: 14 },
  modalBody: { padding: 0 },
  modalScroll: { maxHeight: 560 },
  modalForm: { padding: spacing.lg, gap: spacing.md },
  formGroup: { gap: spacing.sm },
  formLabel: { color: colors.ink, fontSize: type.caption, lineHeight: 14, fontWeight: "800" },
  formInput: { width: "100%" },
  formInputText: { fontSize: type.label, lineHeight: 16 },
  formHint: { color: colors.inkMuted, fontSize: type.micro, lineHeight: 15 },
  formError: { color: colors.danger, fontSize: type.micro, lineHeight: 15, fontWeight: "700" },
  modalSelect: { minHeight: 50, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, backgroundColor: colors.white, alignItems: "center", justifyContent: "space-between", flexDirection: "row", gap: spacing.sm },
  modalSelectCopy: { flex: 1, minWidth: 0, gap: spacing.xs },
  modalSelectTitle: { color: colors.ink, fontSize: type.caption, fontWeight: "700" },
  modalSelectMeta: { color: colors.inkSubtle, fontSize: type.micro },
  modalOptionMenu: { maxHeight: 190, borderWidth: 1, borderColor: colors.line, borderRadius: radius.sm, backgroundColor: colors.white, flexGrow: 0 },
  modalOptionMenuContent: { paddingVertical: spacing.xs },
  modalOption: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, gap: spacing.xs },
  modalOptionActive: { backgroundColor: colors.surfaceTint },
  modalOptionTitle: { color: colors.inkMuted, fontSize: type.micro, fontWeight: "700" },
  modalOptionTitleActive: { color: colors.primary, fontWeight: "900" },
  modalOptionMeta: { color: colors.inkSubtle, fontSize: type.micro },
  stockSnapshot: { minHeight: 38, paddingHorizontal: spacing.md, borderRadius: radius.sm, backgroundColor: colors.surfaceTint, alignItems: "center", gap: spacing.sm },
  stockSnapshotText: { color: colors.inkMuted, fontSize: type.caption },
  stockSnapshotStrong: { color: colors.ink, fontSize: type.caption, lineHeight: 15, fontWeight: "800" },
  inputPrefix: { color: colors.inkMuted, fontSize: type.caption, fontWeight: "800" },
  segmentedControl: { minHeight: 40, borderWidth: 1, borderColor: colors.line, borderRadius: radius.sm, overflow: "hidden" },
  segment: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.sm },
  segmentActive: { backgroundColor: colors.surfaceTint },
  segmentText: { color: colors.inkMuted, fontSize: type.micro, fontWeight: "700" },
  segmentTextActive: { color: colors.primary, fontWeight: "900" },
  summaryBox: { padding: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, backgroundColor: colors.surfaceContainerLow, gap: spacing.sm },
  summaryLine: { alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  summaryLineLabel: { color: colors.inkMuted, fontSize: type.caption },
  summaryLineValue: { color: colors.ink, fontSize: type.caption, fontWeight: "800" },
  fundingRow: { gap: spacing.sm },
  fundingButton: { flex: 1, minHeight: 44, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.xs },
  fundingButtonActive: { borderColor: colors.primary, backgroundColor: colors.surfaceTint },
  fundingText: { color: colors.inkMuted, fontSize: type.caption, fontWeight: "800" },
  fundingTextActive: { color: colors.primary, fontWeight: "900" },
  selectedItemBanner: { padding: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, alignItems: "center", gap: spacing.sm },
  largeAvatar: { width: 40, height: 40, borderRadius: radius.sm, backgroundColor: colors.surfaceTint, alignItems: "center", justifyContent: "center" },
  largeAvatarText: { color: colors.primary, fontSize: type.caption, fontWeight: "900" },
  selectedItemCopy: { flex: 1, minWidth: 0, gap: spacing.xs },
  selectedItemName: { color: colors.ink, fontSize: type.label, fontWeight: "900" },
  selectedItemMeta: { color: colors.inkSubtle, fontSize: type.micro },
  selectedItemStatus: { fontSize: type.micro, fontWeight: "900" },
  textWarning: { color: colors.warning },
  textSuccess: { color: colors.success },
  directionRow: { gap: spacing.sm },
  directionButton: { flex: 1, minHeight: 44, paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.xs },
  directionButtonActive: { borderColor: colors.primary, backgroundColor: colors.surfaceTint },
  directionButtonDangerActive: { borderColor: colors.danger, backgroundColor: colors.dangerSoft },
  directionText: { color: colors.inkMuted, fontSize: type.caption, fontWeight: "800" },
  directionTextActive: { color: colors.primary, fontWeight: "900" },
  directionTextDangerActive: { color: colors.danger, fontWeight: "900" },
  quantityStepperRow: { width: "100%", minHeight: 50, alignItems: "center", borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, backgroundColor: colors.white, overflow: "hidden" },
  stepperButton: { width: 48, height: 48, borderWidth: 0, borderRadius: 0, backgroundColor: colors.surfaceContainerLow, alignItems: "center", justifyContent: "center" },
  stepperInput: { flex: 1, minWidth: 0, minHeight: 48, borderWidth: 0, borderRadius: 0, backgroundColor: colors.white },
  centerInput: { textAlign: "center", fontSize: type.label, lineHeight: 16, fontWeight: "800" },
  equationRow: { alignItems: "center", justifyContent: "center", gap: spacing.sm },
  equationHint: { width: "100%", textAlign: "center" },
  equationValue: { color: colors.ink, fontSize: type.body, fontWeight: "800", fontVariant: ["tabular-nums"] },
  equationOperator: { color: colors.inkSubtle, fontSize: type.bodySmall, fontWeight: "700" },
  modalFooter: { width: "100%", padding: spacing.lg, borderTopWidth: 1, borderTopColor: colors.line, alignItems: "stretch", justifyContent: "center", flexDirection: "column" },
  saveButton: { width: "100%", minHeight: 48, paddingHorizontal: spacing.lg, borderRadius: radius.pill, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" },
  saveButtonDisabled: { opacity: 0.45 },
  saveButtonText: { color: colors.white, fontSize: type.caption, fontWeight: "900" },
  toast: { position: "absolute", right: spacing.lg, bottom: spacing.lg, maxWidth: 360, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.ink, alignItems: "center", flexDirection: "row", gap: spacing.sm, shadowColor: colors.ink, shadowOpacity: 0.18, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 5 },
  toastError: { backgroundColor: colors.danger },
  toastCopy: { flex: 1, minWidth: 0, gap: spacing.xs },
  toastTitle: { color: colors.white, fontSize: type.caption, fontWeight: "900" },
  toastMessage: { color: "rgba(255,255,255,0.78)", fontSize: type.micro, lineHeight: 14 },
});
